name: ce-coffee
namespace: default
runtime: nodejs14
source:
    sourceType: inline
subscriptions:
    - name: ce-coffee
      protocol: ""
      filter:
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.commerce.coffee.required.v1
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.commerce.coffee.produced.v1
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: sap.kyma.custom.commerce.coffee.consumed.v1