apiVersion: apps/v1
kind: Deployment
metadata:
  name: bird-classification-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bird-classification-app
  template:
    metadata:
      labels:
        app: bird-classification-app
    spec:
      containers:
      - name: bird-classification-app
        image: deepan13/bird-classification-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: aws-secret-access-key
---
apiVersion: v1
kind: Service
metadata:
  name: bird-classification-service
spec:
  selector:
    app: bird-classification-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000