apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: event-subscription
  namespace: conference-registration
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.app.conference.registration.v1
  protocol: ""
  protocolsettings: {}
  sink: http://event-consumer.conference-registration.svc.cluster.local