kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data
  labels:
    app: mssql
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
