/*
 * This file      : DBMTK_USER_NAME.STEL_PRC_MMPCOVERNOTE.PROCEDURE.sqlscript
 * Converted from : DBMTK_USER_NAME.STEL_PRC_MMPCOVERNOTE.PROCEDURE.plsql
 *
 * Source DBMS          : Oracle, version unknown
 * Source DB servername : -undefined-
 * Target DBMS          : SAP Hana 2 >= SP05 (SQLScript)
 *
 *
 * User config(id=101) : Include default configuration settings in header of generated files: Setting=yes
 * User config(id=423) : Report identifier upper/lowercase analysis: Setting=no
 * User config(id=330) : Case mapping for usernames: Setting=nomap
 * User config(id=331) : Case mapping for names of schema objects (tables,views,columns,indexes,sequences,etc.): Setting=nomap
 * User config(id=332) : Case mapping for names of SQL objects (procedures, functions; not for variables/parameters): Setting=nomap
 * User config(id=335) : Apply case mappings also when source DBMS is case-sensitive for identifiers: Setting=no
 * User config(id=211) : Include an 'ORIGSQL' comment with the original SQL in the converted SQL: Setting=yes
 * User config(id=212) : Max. number of characters of original SQL in 'ORIGSQL' comment: Setting=80
 * User config(id=215) : Append 'NOT CONVERTED' comment to unconverted statements in the converted SQL: Setting=yes
 * User config(id=217) : Report additional details about some conversion categories, either for all files or only the totals: Setting=all
 * User config(id=218) : Report details ordered by functionality or by impact: Setting=functionality
 * User config(id=220) : Datatype to convert Oracle INT, INTEGER or SMALLINT (which have 38-digit precision): Setting=BIGINT
 * User config(id=221) : Length to convert Oracle (VAR)CHAR(2) declared without length: Setting=75
 * User config(id=222) : For variables/parameters, datatype to convert Oracle NUMBER declared without precision: Setting=NUMERIC(38,10)
 * User config(id=223) : For table/view columns, datatype to convert Oracle NUMBER declared without precision: Setting=NUMERIC(38,10)
 * User config(id=224) : For variables/parameters, datatype to convert Oracle NUMBER declared with precision but without scale(see User Guide): Setting=optimized_integer
 * User config(id=225) : For table/view columns, datatype to convert Oracle NUMBER declared with precision but without scale(see User Guide): Setting=optimized_integer
 * User config(id=231) : Length to convert a CHAR/BINARY datatype exceeding the target DBMS length: Setting=MAX
 * User config(id=265) : Convert Oracle packages to Hana User-Defined Libraries: Setting=no
 * User config(id=290) : Default conversion of DBMS_OUTPUT.PUT_LINE/GET_LINE: Setting=print
 * User config(id=292) : Conversion of PRINT-style statements: Setting=sqlscript_print
 * User config(id=300) : Conversion of REF CURSOR output parameters in procedures called from the client app: Setting=table_variable
 * User config(id=310) : Generate a SQL SECURITY/EXECUTE AS clause for procedures/functions: Setting=yes
 * User config(id=320) : Ignore or keep the leading 'N' in Unicode string notation N'...': Setting=ignore
 * User config(id=441) : Generate identity columns as BY DEFAULT or ALWAYS: Setting=by_default
 * User config(id=380) : How aggressively to convert identifiers in SQL objects (higher=slower): Setting=medium
 * User config(id=382) : How to rename identifiers that are reserved words: delimited, or with a suffix: Setting=delimited
 * User config(id=383) : How to handle identifiers that are non-recommended words (e.g. ANSI-reserved): Setting=ignore
 * User config(id=385) : When to substitute a column alias with the expression, when referenced in the query(settings are cumulative): Setting=simple_expression
 * User config(id=600) : Schema for run-time components: Setting=sapdbmtk
 * User config(id=704) : Show warning counts in Hana when running run_ddl/run_sql generated shell scripts: Setting=yes
 * User config(id=720) : Include the original SQL code at the end of the converted file: Setting=no
 * User config(id=781) : Generate call to customizable procedure after each object creation: Setting=yes
 *   NB: Settings marked '*' are set to non-defaults (use config #101=no for condensed overview))
 *
 * Project directory : C:/HANAMigrations/STELEXT
 *
 *-----------------------------------------------------------------------------
 * Generated by SAP Advanced SQL Migration v.3.5.3 at 09-May-2024 20:42:31
 * (generated with: sapdbmtk convert, 64791)
 * SAP Advanced SQL Migration is property of SAP SE.
 *-----------------------------------------------------------------------------
 */
go
CALL sapdbmtk.sp_dbmtk_report_connect('DBMTK_USER_NAME.STEL_PRC_MMPCOVERNOTE.PROCEDURE.sqlscript') WITH HINT(IGNORE_PLAN_CACHE)
go

-- Verify the target database has the expected version (or later).
-- This proc aborts the script if the version is earlier than expected:
CALL sapdbmtk.sp_dbmtk_target_dbms_version_check('HANA', '2SP05', 'DBMTK_USER_NAME.STEL_PRC_MMPCOVERNOTE.PROCEDURE.sqlscript') WITH HINT(IGNORE_PLAN_CACHE)
go
CALL sapdbmtk.sp_dbmtk_hang_session  -- NB: hangs only when waiting for user to abort session with CTRL-C (message is printed first)
go

-- Verify Hana database being used
CALL sapdbmtk.sp_dbmtk_HANA_db_check()
go
CALL sapdbmtk.sp_dbmtk_hang_session  -- NB: hangs only when waiting for user to abort session with CTRL-C (message is printed first)
go

-- Verify we have the required permissions
CALL sapdbmtk.sp_dbmtk_target_permissions_check()
go
CALL sapdbmtk.sp_dbmtk_hang_session  -- NB: hangs only when waiting for user to abort session with CTRL-C (message is printed first)
go
DO BEGIN
	if exists (select * from SYS.USERS where user_name = upper('DBMTK_USER_NAME')) THEN
		EXECUTE IMMEDIATE 'CONNECT DBMTK_USER_NAME PASSWORD "ZThn0&y92!$o8Bbd"';
		SELECT 'Reconnected as user '''||SESSION_USER||'''' FROM SYS.DUMMY;
	END IF;
END
go
SET SCHEMA DBMTK_USER_NAME
go

/********************* Converted SQL code starts here:*************************/

/*
 * This file was extracted from 'C:/HANAMigrations/STELEXT/OracleObjects/STEL_PRC_MMPCOVERNOTE.sql'
 * at 09-May-2024 20:29:14 with the 'extract_offline' command of SAP Advanced SQL Migration v.3.5.3 (64791)
 * User config setting for 'extract_offline' (id=132) was '0'.
 */
go

--********** Creating procedure 'DBMTK_USER_NAME.STEL_PRC_MMPCOVERNOTE' ********************
go

CALL SQLSCRIPT_PRINT:PRINT_LINE( 'Creating procedure ''DBMTK_USER_NAME.STEL_PRC_MMPCOVERNOTE''...' );
go

/* ORIGSQL: CREATE OR REPLACE PROCEDURE STEL_PRC_MMPCOVERNOTE (in_rpttype VARCHAR2, IN_PERIO(...) */
CREATE OR REPLACE PROCEDURE DBMTK_USER_NAME.STEL_PRC_MMPCOVERNOTE
(
    IN in_rpttype VARCHAR(75),   /* RESOLVE: Manual edits required: VARCHAR2 parameter(no length): user-configured length=75; adjust as needed */
                                 /* ORIGSQL: in_rpttype VARCHAR2 */
    IN IN_PERIODSEQ BIGINT,   /* ORIGSQL: IN_PERIODSEQ IN INTEGER */
    IN IN_PROCESSINGUNITSEQ BIGINT     /* ORIGSQL: IN_PROCESSINGUNITSEQ IN INTEGER */
)
LANGUAGE SQLSCRIPT
SQL SECURITY DEFINER
DEFAULT SCHEMA DBMTK_USER_NAME
/*READS SQL DATA*/ -- this procedure cannot be read-only
AS
BEGIN
    /* sapdbmtk: one or more DECLARE statements below were moved upwards, before the first executable statement */
    DECLARE v_Tenant VARCHAR(10) = 'STEL';  /* ORIGSQL: v_Tenant VARCHAR2(10) := 'STEL'; */
    DECLARE v_StMsg VARCHAR(10) = 'START';  /* ORIGSQL: v_StMsg VARCHAR2(10) := 'START'; */
    DECLARE v_EdMsg VARCHAR(10) = 'END';  /* ORIGSQL: v_EdMsg VARCHAR2(10) := 'END'; */
    DECLARE v_ComponentName VARCHAR(100) = NULL;  /* ORIGSQL: v_ComponentName VARCHAR2(100) := NULL; */
    DECLARE v_CalendarName VARCHAR(100) = NULL;  /* ORIGSQL: v_CalendarName VARCHAR2(100) := NULL; */
    DECLARE v_PeriodName VARCHAR(100) = NULL;  /* ORIGSQL: v_PeriodName VARCHAR2(100) := NULL; */
    DECLARE v_eot CONSTANT TIMESTAMP = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200', 'MM/DD/YYYY');  /* ORIGSQL: v_eot CONSTANT DATE := TO_DATE('01/01/2200', 'MM/DD/YYYY') ; */

    v_ComponentName = 'STEL_PRC_MMPCOVERNOTE';

    -- Add debug Log for Process START
    /* ORIGSQL: STEL_log (v_Tenant, v_ComponentName, v_StMsg || ' PeriodSeq - ' || in_PeriodSeq (...) */
    CALL DBMTK_USER_NAME.STEL_LOG(:v_Tenant, :v_ComponentName, IFNULL(:v_StMsg,'') || ' PeriodSeq - '|| IFNULL(TO_VARCHAR(:IN_PERIODSEQ),'') || ' PU - '|| IFNULL(TO_VARCHAR(:IN_PROCESSINGUNITSEQ),''));

    /* ORIGSQL: COMMIT; */
    COMMIT;

    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_PERIODCALENDAR' not found */

    SELECT
        CALENDARNAME,
        PERIODNAME
    INTO
        v_CalendarName,
        v_PeriodName
    FROM
        cs_periodcalendar
    WHERE
        PERIODSEQ = :IN_PERIODSEQ;

    /* ORIGSQL: DELETE STEL_RPT_MMPCOVERNOTE_TMP WHERE PERIODSEQ = IN_PERIODSEQ AND PROCESSINGUN(...) */
    DELETE
    FROM
        STEL_RPT_MMPCOVERNOTE_TMP
    WHERE
        PERIODSEQ = :IN_PERIODSEQ
        AND PROCESSINGUNITSEQ = :IN_PROCESSINGUNITSEQ;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    -- Deleting  table data 
    /* ORIGSQL: DELETE STEL_RPT_MMPCOVERNOTE WHERE PERIODSEQ = IN_PERIODSEQ AND PROCESSINGUNITSE(...) */
    DELETE
    FROM
        STEL_RPT_MMPCOVERNOTE
    WHERE
        PERIODSEQ = :IN_PERIODSEQ
        AND PROCESSINGUNITSEQ = :IN_PROCESSINGUNITSEQ;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    /* ORIGSQL: STEL_PROC_RPT_partitions (IN_PERIODSEQ, 'STEL_RPT_MMPCOVERNOTE') */
    CALL DBMTK_USER_NAME.STEL_PROC_RPT_PARTITIONS(:IN_PERIODSEQ, 'STEL_RPT_MMPCOVERNOTE');

    -- managing table partitions

    -- FTTH data insertion

    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_PARTICIPANT' not found */
    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_POSITION' not found */
    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_PERIOD' not found */
    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_PROCESSINGUNIT' not found */
    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_DEPOSIT' not found */
    /* ORIGSQL: INSERT INTO STEL_RPT_MMPCOVERNOTE_TMP (TENANTID, PERIODSEQ, PROCESSINGUNITSEQ, P(...) */
    INSERT INTO STEL_RPT_MMPCOVERNOTE_TMP
        (
            TENANTID,
            PERIODSEQ,
            PROCESSINGUNITSEQ,
            PERIODNAME,
            PROCESSINGUNITNAME,
            CALENDARNAME,
            POSITIONSEQ,
            PAYEESEQ,
            VENDOR_NAME,
            PRODUCT_NAME,
            PAYOUT,
            CREATEDATE,
            reportperiodname,
            EARNINGCodeID,
            GROUPLABEL
        )
        
            SELECT   /* ORIGSQL: (SELECT v_Tenant, IN_PERIODSEQ, IN_PROCESSINGUNITSEQ, v_PeriodName, PRC.NAME, v_(...) */
                :v_Tenant,
                :IN_PERIODSEQ,
                :IN_PROCESSINGUNITSEQ,
                :v_PeriodName,
                PRC.NAME,
                :v_CalendarName,
                PMT.POSITIONSEQ,
                PMT.PAYEESEQ,
                PRT.LASTNAME AS VENDOR_NAME,
                CASE
                    WHEN PMT.EARNINGGROUPID LIKE '%DEL%'
                    THEN 'DEL Fixed Line VAS Incentive'
                    ELSE 'FTTH Activation Incentive'
                END,
                SUM(PMT.VALUE) AS VALUE,
                CURRENT_TIMESTAMP,  /* ORIGSQL: SYSDATE */
                EARNINGGROUPID,
                CASE
                    WHEN EARNINGCodeID = 'Commission_Distributor Incentive'
                    THEN IFNULL(TO_VARCHAR(sapdbmtk.sp_f_dbmtk_truncate_datetime(prd.startdate, 'Q'),'Mon'),'')  /* ORIGSQL: TRUNC(prd.startdate, 'Q') */
                                                                                                                                  /* ORIGSQL: TO_CHAR(TRUNC (prd.startdate, 'Q'), 'Mon') */
                    || ' - '
                    || IFNULL(TO_VARCHAR(sapdbmtk.sp_f_dbmtk_truncate_datetime(prd.startdate, 'MM'),'Mon'),'')  /* ORIGSQL: TRUNC(prd.startdate, 'MM') */
                                                                                                                /* ORIGSQL: TO_CHAR(TRUNC (prd.startdate, 'MM'), 'Mon') */
                    || ' '
                    || IFNULL(TO_VARCHAR(prd.startdate,'YYYY'),'')  /* ORIGSQL: TO_CHAR(prd.startdate, 'YYYY') */
                    ELSE :v_PeriodName
                END,
                /* --POS.GENERICATTRIBUTE11 */
                lkp.StringValue
            FROM
                CS_PARTICIPANT PRT,
                CS_POSITION POS,
                CS_PERIOD PRD,
                CS_PROCESSINGUNIT PRC,
                -- CS_PAYMENT PMT
                CS_DEPOSIT PMT,
                (
                    SELECT   /* ORIGSQL: (SELECT dim0, stringvalue, effectivestartdate, effectiveenddate FROM stel_lookup(...) */
                        dim0,
                        stringvalue,
                        effectivestartdate,
                        effectiveenddate
                    FROM
                        stel_lookup lk
                    WHERE
                        lk.name LIKE 'LT_Dealer_Channel Type'
                ) AS lkp
            WHERE
                PRT.REMOVEDATE = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200', 'MM/DD/YYYY')  /* ORIGSQL: TO_DATE('01/01/2200', 'MM/DD/YYYY') */
                AND PRT.effectivestartdate <= prd.enddate
                AND PRT.effectiveenddate > prd.enddate
                AND pos.effectivestartdate <= prd.enddate
                AND pos.effectiveenddate > prd.enddate
                AND pos.REMOVEDATE = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200', 'MM/DD/YYYY')  /* ORIGSQL: TO_DATE('01/01/2200', 'MM/DD/YYYY') */
                AND PRT.PAYEESEQ = POS.PAYEESEQ
                --and lkp.dim0=pos.name
                AND lkp.dim0 = REPLACE(pos.name, ' - ', '-')
                AND lkp.effectivestartdate <= prd.enddate
                AND lkp.effectiveenddate > prd.enddate
                AND PRD.PERIODSEQ = :IN_PERIODSEQ
                AND PMT.PERIODSEQ = PRD.PERIODSEQ
                AND PMT.EARNINGGROUPID IN
                ('Commission_MMP_FTTH & VAS',
                    'Commission_MMP_FTTH & VAS',
                    'Commission_SER',
                    --,'Commission_MMP_DEL VAS',
                    'Commission',
                    -- 'Commission_MMP_MioTV',
                'Commission_MMP_Smart Home')
                AND PRC.PROCESSINGUNITSEQ = :IN_PROCESSINGUNITSEQ
                AND PRC.PROCESSINGUNITSEQ = PMT.PROCESSINGUNITSEQ
                AND PRT.PAYEESEQ = PMT.PAYEESEQ
            GROUP BY
                :v_Tenant,
                :IN_PERIODSEQ,
                :IN_PROCESSINGUNITSEQ,
                :v_PeriodName,
                PRC.NAME,
                :v_CalendarName,
                PMT.POSITIONSEQ,
                PMT.PAYEESEQ,
                PRT.LASTNAME,
                EARNINGGROUPID,
                CASE
                    WHEN EARNINGCodeID = 'Commission_Distributor Incentive'
                    THEN IFNULL(TO_VARCHAR(sapdbmtk.sp_f_dbmtk_truncate_datetime(prd.startdate, 'Q'),'Mon'),'')  /* ORIGSQL: TRUNC(prd.startdate, 'Q') */
                                                                                                                                  /* ORIGSQL: TO_CHAR(TRUNC (prd.startdate, 'Q'), 'Mon') */
                    || ' - '
                    || IFNULL(TO_VARCHAR(sapdbmtk.sp_f_dbmtk_truncate_datetime(prd.startdate, 'MM'),'Mon'),'')  /* ORIGSQL: TRUNC(prd.startdate, 'MM') */
                                                                                                                /* ORIGSQL: TO_CHAR(TRUNC (prd.startdate, 'MM'), 'Mon') */
                    || ' '
                    || IFNULL(TO_VARCHAR(prd.startdate,'YYYY'),'')  /* ORIGSQL: TO_CHAR(prd.startdate, 'YYYY') */
                    ELSE :v_PeriodName
                END,
                --POS.GENERICATTRIBUTE11
                lkp.stringvalue
        ;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    --DEL VAS 
    /* ORIGSQL: INSERT INTO STEL_RPT_MMPCOVERNOTE_TMP (TENANTID, PERIODSEQ, PROCESSINGUNITSEQ, P(...) */
    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_CREDIT' not found */
    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_PMCREDITTRACE' not found */
    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_MEASUREMENT' not found */
    INSERT INTO STEL_RPT_MMPCOVERNOTE_TMP
        (
            TENANTID,
            PERIODSEQ,
            PROCESSINGUNITSEQ,
            PERIODNAME,
            PROCESSINGUNITNAME,
            CALENDARNAME,
            POSITIONSEQ,
            PAYEESEQ,
            VENDOR_NAME,
            PRODUCT_NAME,
            PAYOUT,
            CREATEDATE,
            reportperiodname,
            EARNINGCodeID,
            GROUPLABEL
        )
        SELECT   /* ORIGSQL: SELECT v_Tenant, IN_PERIODSEQ, IN_PROCESSINGUNITSEQ, v_PeriodName, 'Singtel_PU',(...) */
            :v_Tenant,
            :IN_PERIODSEQ,
            :IN_PROCESSINGUNITSEQ,
            :v_PeriodName,
            'Singtel_PU',
            :v_CalendarName,
            c.POSITIONSEQ,
            c.PAYEESEQ,
            Par.LASTNAME AS VENDOR_NAME,
            CASE
                WHEN c.genericattribute16 = 'DEL'
                THEN 'Fixed Line VAS (DEL)'
                WHEN c.genericattribute16 = 'HDL'
                THEN 'Fixed Line VAS (MioVoice)'
                ELSE 'Product not found'
            END,
            SUM(c.VALUE) AS VALUE,
            CURRENT_TIMESTAMP,  /* ORIGSQL: SYSDATE */
            'Commission_MMP_DEL VAS' AS EARNINGGROUPID,
            pd.name AS v_periodName,
            /* --POS.GENERICATTRIBUTE11 */
            lkp.StringValue
        FROM
            cs_credit c
        INNER JOIN
            cs_pmcredittrace pmt
            ON pmt.creditseq = c.creditseq
        INNER JOIN
            cs_measurement m
            ON m.measurementseq = pmt.measurementseq
        INNER JOIN
            cs_period pd
            ON pd.periodseq = c.periodseq
            AND pd.periodseq = m.periodseq
            AND pd.periodseq = pmt.targetperiodseq
        INNER JOIN
            cs_position pos
            ON pos.ruleelementownerseq = c.positionseq
            AND pos.removedate = :v_eot
            AND TO_DATE(ADD_SECONDS(pd.enddate,(86400*-1))) BETWEEN pos.effectivestartdate AND TO_DATE(ADD_SECONDS(pos.effectiveenddate,(86400*-1)))   /* ORIGSQL: pos.effectiveenddate - 1 */
                                                                                                                                                       /* ORIGSQL: pd.enddate - 1 */
        INNER JOIN
            cs_participant par
            ON par.payeeseq = m.payeeseq
            AND par.removedate = :v_eot
            AND TO_DATE(ADD_SECONDS(pd.enddate,(86400*-1))) BETWEEN par.effectivestartdate AND TO_DATE(ADD_SECONDS(par.effectiveenddate,(86400*-1)))   /* ORIGSQL: pd.enddate - 1 */
                                                                                                                                                       /* ORIGSQL: par.effectiveenddate - 1 */
        INNER JOIN
            (
                SELECT   /* ORIGSQL: (SELECT dim0, stringvalue, effectivestartdate, effectiveenddate FROM stel_lookup(...) */
                    dim0,
                    stringvalue,
                    effectivestartdate,
                    effectiveenddate
                FROM
                    stel_lookup lk
                WHERE
                    lk.name LIKE 'LT_Dealer_Channel Type'
            ) AS lkp
            ON lkp.dim0 = REPLACE(pos.name, ' - ', '-')
            AND lkp.effectivestartdate <= pd.enddate
            AND lkp.effectiveenddate > pd.enddate
        WHERE
            m.name = 'PM_MMP_DEL Fixed Line VAS'
            --and c.genericattribute16 in ( 'DEL','HDL')
            AND pd.periodseq = :IN_PERIODSEQ
            AND c.processingunitseq = :IN_PROCESSINGUNITSEQ
            AND m.processingunitseq = :IN_PROCESSINGUNITSEQ
            AND pmt.processingunitseq = :IN_PROCESSINGUNITSEQ
            AND m.positionseq = c.positionseq
            AND m.tenantid = :v_Tenant
            AND c.tenantid = :v_Tenant
            AND pmt.tenantid = :v_Tenant
        GROUP BY
            :v_Tenant,
            :IN_PERIODSEQ,
            :IN_PROCESSINGUNITSEQ,
            :v_PeriodName,
            'Singtel_PU',
            :v_CalendarName,
            c.POSITIONSEQ,
            c.PAYEESEQ,
            Par.LASTNAME,
            CASE
                WHEN c.genericattribute16 = 'DEL'
                THEN 'Fixed Line VAS (DEL)'
                WHEN c.genericattribute16 = 'HDL'
                THEN 'Fixed Line VAS (MioVoice)'
                ELSE 'Product not found'
            END,
            CURRENT_TIMESTAMP,  /* ORIGSQL: SYSDATE */
            'Commission_MMP_DEL VAS',
            pd.name,
            --POS.GENERICATTRIBUTE11
            lkp.StringValue;

    -- MioTV data insertion      

    /* ORIGSQL: INSERT INTO STEL_RPT_MMPCOVERNOTE_TMP (TENANTID, PERIODSEQ, PROCESSINGUNITSEQ, P(...) */
    INSERT INTO STEL_RPT_MMPCOVERNOTE_TMP
        (
            TENANTID,
            PERIODSEQ,
            PROCESSINGUNITSEQ,
            PERIODNAME,
            PROCESSINGUNITNAME,
            CALENDARNAME,
            POSITIONSEQ,
            PAYEESEQ,
            VENDOR_NAME,
            PRODUCT_NAME,
            PAYOUT,
            CREATEDATE,
            EARNINGCodeID,
            GROUPLABEL
        )
        
            SELECT   /* ORIGSQL: (SELECT v_Tenant, IN_PERIODSEQ, IN_PROCESSINGUNITSEQ, v_PeriodName, NAME, v_Cale(...) */
                :v_Tenant,/* -- Modified by sudhir/gopi defect #97 */  :IN_PERIODSEQ,
                :IN_PROCESSINGUNITSEQ,
                :v_PeriodName,
                NAME,
                :v_CalendarName,
                POSITIONSEQ,
                PAYEESEQ,
                VENDOR_NAME,
                'Singtel TV Activation Incentive',
                SUM(VALUE),
                CURRENT_TIMESTAMP,  /* ORIGSQL: SYSDATE */
                EARNINGGROUPID,
                stringValue
            FROM
                (
                    SELECT   /* ORIGSQL: (SELECT v_Tenant, IN_PERIODSEQ, IN_PROCESSINGUNITSEQ, v_PeriodName, PRC.NAME, v_(...) */
                        :v_Tenant,
                        :IN_PERIODSEQ,
                        :IN_PROCESSINGUNITSEQ,
                        :v_PeriodName,
                        PRC.NAME,
                        :v_CalendarName,
                        PMT.POSITIONSEQ,
                        PMT.PAYEESEQ,
                        PRT.LASTNAME AS VENDOR_NAME,
                        'Singtel TV Activation Incentive',
                        PMT.VALUE,
                        CURRENT_TIMESTAMP,  /* ORIGSQL: SYSDATE */
                        EARNINGGROUPID,
                        /* -- POS.GENERICATTRIBUTE11 */
                        lkp.stringValue
                    FROM
                        CS_PARTICIPANT PRT,
                        CS_POSITION POS,
                        CS_PERIOD PRD,
                        CS_PROCESSINGUNIT PRC,
                        CS_DEPOSIT PMT,
                        (
                            SELECT   /* ORIGSQL: (SELECT dim0, stringvalue, effectivestartdate, effectiveenddate FROM stel_lookup(...) */
                                dim0,
                                stringvalue,
                                effectivestartdate,
                                effectiveenddate
                            FROM
                                stel_lookup lk
                            WHERE
                                lk.name LIKE 'LT_Dealer_Channel Type'
                        ) AS lkp
                    WHERE
                        PRT.REMOVEDATE = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200', 'MM/DD/YYYY')  /* ORIGSQL: TO_DATE('01/01/2200', 'MM/DD/YYYY') */
                        AND PRT.effectivestartdate <= prd.enddate
                        AND PRT.effectiveenddate > prd.enddate
                        AND pos.effectivestartdate <= prd.enddate
                        AND pos.effectiveenddate > prd.enddate
                        AND pos.REMOVEDATE = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200', 'MM/DD/YYYY')  /* ORIGSQL: TO_DATE('01/01/2200', 'MM/DD/YYYY') */
                        AND PRT.PAYEESEQ = POS.PAYEESEQ
                        AND lkp.dim0 = REPLACE(pos.name, ' - ', '-')
                        --and lkp.dim0=pos.name
                        AND lkp.effectivestartdate <= prd.enddate
                        AND lkp.effectiveenddate > prd.enddate
                        AND PRD.PERIODSEQ = :IN_PERIODSEQ
                        AND PMT.PERIODSEQ = PRD.PERIODSEQ
                        AND PMT.EARNINGGROUPID IN ('Commission_MMP_MioTV')
                        AND PRC.PROCESSINGUNITSEQ = :IN_PROCESSINGUNITSEQ
                        AND PRC.PROCESSINGUNITSEQ = PMT.PROCESSINGUNITSEQ
                        AND PRT.PAYEESEQ = PMT.PAYEESEQ
                    GROUP BY
                        :v_Tenant,
                        :IN_PERIODSEQ,
                        :IN_PROCESSINGUNITSEQ,
                        :v_PeriodName,
                        PRC.NAME,
                        :v_CalendarName,
                        PMT.POSITIONSEQ,
                        PMT.PAYEESEQ,
                        PRT.LASTNAME,
                        PMT.VALUE,
                        EARNINGGROUPID,
                        --POS.GENERICATTRIBUTE11
                        lkp.stringValue
                ) AS dbmtk_corrname_23977
            GROUP BY
                :v_Tenant,
                :IN_PERIODSEQ,
                :IN_PROCESSINGUNITSEQ,
                :v_PeriodName,
                NAME,
                :v_CalendarName,
                POSITIONSEQ,
                PAYEESEQ,
                VENDOR_NAME,
                EARNINGGROUPID,
                stringValue
        ;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    -- Integrated Sales Incentivedata insertion    

    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_INCENTIVE' not found */
    /* ORIGSQL: INSERT INTO STEL_RPT_MMPCOVERNOTE_TMP (TENANTID, PERIODSEQ, PROCESSINGUNITSEQ, P(...) */
    INSERT INTO STEL_RPT_MMPCOVERNOTE_TMP
        (
            TENANTID,
            PERIODSEQ,
            PROCESSINGUNITSEQ,
            PERIODNAME,
            PROCESSINGUNITNAME,
            CALENDARNAME,
            POSITIONSEQ,
            PAYEESEQ,
            VENDOR_NAME,
            PRODUCT_NAME,
            PAYOUT,
            CREATEDATE,
            EARNINGCodeID,
            GROUPLABEL
        )
        SELECT   /* ORIGSQL: (SELECT v_Tenant, IN_PERIODSEQ, IN_PROCESSINGUNITSEQ, v_PeriodName, PRC.NAME, v_(...) */
            :v_Tenant,
            :IN_PERIODSEQ,
            :IN_PROCESSINGUNITSEQ,
            :v_PeriodName,
            PRC.NAME,
            :v_CalendarName,
            PMT.POSITIONSEQ,
            PMT.PAYEESEQ,
            PRT.LASTNAME AS VENDOR_NAME,
            'Singtel TV, FTTH & Mobile Vas',
            SUM(PMT.VALUE) AS VALUE,
            CURRENT_TIMESTAMP,  /* ORIGSQL: SYSDATE */
            'Singtel TV, FTTH & Mobile Vas',
            /* -- POS.GENERICATTRIBUTE11 */
            lkp.stringValue
        FROM
            CS_PARTICIPANT PRT,
            CS_POSITION POS,
            CS_PERIOD PRD,
            CS_PROCESSINGUNIT PRC,
            CS_INCENTIVE PMT,
            (
                SELECT   /* ORIGSQL: (SELECT dim0, stringvalue, effectivestartdate, effectiveenddate FROM stel_lookup(...) */
                    dim0,
                    stringvalue,
                    effectivestartdate,
                    effectiveenddate
                FROM
                    stel_lookup lk
                WHERE
                    lk.name LIKE 'LT_Dealer_Channel Type'
                    AND dim0 IN('D2615','D2643')
            ) AS lkp
        WHERE
            PRT.REMOVEDATE = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200', 'MM/DD/YYYY')  /* ORIGSQL: TO_DATE('01/01/2200', 'MM/DD/YYYY') */
            AND PRT.effectivestartdate <= prd.enddate
            AND PRT.effectiveenddate > prd.enddate
            AND pos.effectivestartdate <= prd.enddate
            AND pos.effectiveenddate > prd.enddate
            AND pos.REMOVEDATE = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200', 'MM/DD/YYYY')  /* ORIGSQL: TO_DATE('01/01/2200', 'MM/DD/YYYY') */
            AND PRT.PAYEESEQ = POS.PAYEESEQ
            --AND lkp.dim0 = REPLACE (pos.name, ' - ', '-')  --[arun/avinash - commented based on idscussion on 22Aug2019]
            --and lkp.dim0=pos.name
            AND lkp.effectivestartdate <= prd.enddate
            AND lkp.effectiveenddate > prd.enddate
            AND PRD.PERIODSEQ = :IN_PERIODSEQ
            AND PMT.PERIODSEQ = PRD.PERIODSEQ
            -- AND PMT.EARNINGGROUPID IN ('Commission_MMP_DH Telesales_Bonus')
            AND PMT.GENERICATTRIBUTE1 IN
            ('MMP_DH Telesales_North Star Integrated Team_Bonus','MMP_DH Telesales_Telecontinent Integrated Team_Bonus')
            AND PRC.PROCESSINGUNITSEQ = :IN_PROCESSINGUNITSEQ
            AND PRC.PROCESSINGUNITSEQ = PMT.PROCESSINGUNITSEQ
            AND PRT.PAYEESEQ = PMT.PAYEESEQ
        GROUP BY
            :v_Tenant,
            :IN_PERIODSEQ,
            :IN_PROCESSINGUNITSEQ,
            :v_PeriodName,
            PRC.NAME,
            :v_CalendarName,
            PMT.POSITIONSEQ,
            PMT.PAYEESEQ,
            PRT.LASTNAME,
            --POS.GENERICATTRIBUTE11
            lkp.stringValue
    ;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    -- Adding summary records into final reporting table.
    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.STEL_RPT_MMPCOVERNOTE_TMP' not found */
    /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.STEL_RPT_MMPCOVERNOTE' not found */

    /* ORIGSQL: INSERT INTO STEL_RPT_MMPCOVERNOTE (TENANTID, PERIODSEQ, PROCESSINGUNITSEQ, PERIO(...) */
    INSERT INTO STEL_RPT_MMPCOVERNOTE
        (
            TENANTID,
            PERIODSEQ,
            PROCESSINGUNITSEQ,
            PERIODNAME,
            PROCESSINGUNITNAME,
            CALENDARNAME,
            POSITIONSEQ,
            PAYEESEQ,
            VENDOR_NAME,
            PRODUCT_NAME,
            PAYOUT,
            GROUPLABEL
        )
        SELECT   /* ORIGSQL: (SELECT TENANTID, PERIODSEQ, PROCESSINGUNITSEQ, PERIODNAME, PROCESSINGUNITNAME, (...) */
            TENANTID,
            PERIODSEQ,
            PROCESSINGUNITSEQ,
            PERIODNAME,
            PROCESSINGUNITNAME,
            CALENDARNAME,
            POSITIONSEQ,
            PAYEESEQ,
            VENDOR_NAME,
            PRODUCT_NAME,
            SUM(PAYOUT) AS PAYOUT,
            GROUPLABEL
        FROM
            STEL_RPT_MMPCOVERNOTE_TMP
        WHERE
            PERIODSEQ = :IN_PERIODSEQ
            AND PROCESSINGUNITSEQ = :IN_PROCESSINGUNITSEQ
        GROUP BY
            TENANTID,
            PERIODSEQ,
            PROCESSINGUNITSEQ,
            PERIODNAME,
            PROCESSINGUNITNAME,
            CALENDARNAME,
            POSITIONSEQ,
            PAYEESEQ,
            VENDOR_NAME,
            PRODUCT_NAME,
            GROUPLABEL
    ;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    -- Add debug Log for Process END
    /* ORIGSQL: STEL_log (v_Tenant, v_ComponentName, v_EdMsg || ' PeriodSeq - ' || in_PeriodSeq (...) */
    CALL DBMTK_USER_NAME.STEL_LOG(:v_Tenant, :v_ComponentName, IFNULL(:v_EdMsg,'') || ' PeriodSeq - '|| IFNULL(TO_VARCHAR(:IN_PERIODSEQ),'') || ' PU - '|| IFNULL(TO_VARCHAR(:IN_PROCESSINGUNITSEQ),''));

    /* ORIGSQL: COMMIT; */
    COMMIT;
END;
go
CALL sapdbmtk.sp_dbmtk_object_install_custom('procedure', 'DBMTK_USER_NAME', 'STEL_PRC_MMPCOVERNOTE') WITH HINT(IGNORE_PLAN_CACHE);
go

/*
 * end of 'DBMTK_USER_NAME.STEL_PRC_MMPCOVERNOTE.PROCEDURE.sqlscript'
 */
go

