apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: daprwishlistappsdk
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - DELETE
      path: /.*
  service:
    host: daprwishlistapp
    name: daprwishlistapp
    port: 7080
