Feature: request feedback

Scenario: Test complete flow for request feedback
  Given I logged in
  Given I open chat window and reset conversation "true"
  When I send messgae "request feedback from alex"
  When I click "ui5-button" "Select"
  Then I should find "What's the feedback topic?" in "span"
  When I send messgae "test topic"
  Then I should find "Do you want to make changes to the questions?" in "span"
  When I click "ui5-button" "No"
  Then I should find "Would you like to send your feedback request?" in "span"
  When I click "ui5-button" "Yes"
  Then I should find "Okay, your feedback request has been sent." in "span"
  Then I should find "View Feedback" in "ui5-illustrated-message"

  Given I reset conversation
  When I send messgae "request feedback from TEST"
  Then I should find "From whom?" in "span"
  When I send messgae "rondo"
  Then I should find "Sorry, I didn't find rondo. Let's try something else." in "span"

  Given I reset conversation
  When I send messgae "request feedback from alex"
  Then I should find "Please select which employee." in "span"
  When I send messgae "linjie"
  Then I should find "Sorry, I didn't find linjie. Could you try again?" in "span"
  When I click "ui5-button" "Select"
  Then I should find "What's the feedback topic?" in "span"
  When I send dummy messgae with length "201"
  Then I should find "Oops, your input has exceeded the maximum limit of 200 characters. Please try again." in "span"
  When I send messgae "test topic"
  Then I should find "Do you want to make changes to the questions?" in "span"
  When I click "ui5-button" "Yes"
  Then I should find "Which question would you like to change?" in "span"
  When I send messgae "q1"
  Then I should find "You can only select a question from this list." in "span"
  When I click "ui5-li-custom" "What are my strengths?"
  Then I should find "What is the new question?" in "span"
  When I send dummy messgae with length "251"
  Then I should find "Oops, your input has exceeded the maximum limit of 250 characters. Please try again." in "span"
  When I send messgae "q1"
  Then I should find "Okay. Any other changes?" in "span"
  When I click "ui5-li-custom" "q1"
  Then I should find "What is the new question?" in "span"
  When I send messgae "What are my strengths?"
  Then I should find "Okay. Any other changes?" in "span"
  When I send messgae "done"
  Then I should find "Would you like to send your feedback request?" in "span"
  When I click "ui5-button" "Yes"
  Then I should find "Okay, your feedback request has been sent." in "span"
  Then I should find "View Feedback" in "ui5-illustrated-message"