--liquibase formatted sql

--changeset jcadby:KYN_Schedule1 splitStatements:false stripComments:false
--comment: Create table
create table EXT.KYN_Schedule (
  schedule_key bigint not null generated by default as identity,
  name varchar(255) not null,
  call_sql clob not null,
  call_order integer not null default 0,
  active tinyint not null default 1,
  months integer not null default 0,
  days integer not null default 0,
  hours integer not null default 0,
  minutes integer not null default 0,
  start_date seconddate not null default current_timestamp,
  end_date seconddate not null default '2200-01-01',
  due_date seconddate,
  last_due_date seconddate,
  last_run_date timestamp,
  message varchar(1000),
  primary key (
    schedule_key
  )  
);

--changeset jcadby:KYN_Schedule2 splitStatements:false stripComments:false
--comment: Inserts
do begin
  delete from ext.KYN_Schedule;
  insert into ext.KYN_Schedule (name, call_sql, start_date, hours) values ('REPDAILY', 'call EXT.KYN_Prc_Report_Run()', '2023-01-01 16:00:00', 2);
  --insert into ext.KYN_Schedule (name, call_sql, start_date, minutes) values ('JC_TEST', 'call EXT.KYN_Prc_debug(''schedule test'')', '2023-01-01 16:00:00', 1);
  commit;
end;