CREATE procedure sp_update_batch_status (in P_BATCH_NO INTEGER, in P_STR_STATUS VARCHAR2(255))
  as 
    begin
    DECLARE STR_STATUS_START CONSTANT VARCHAR(20) = 'start';  /* ORIGSQL: STR_STATUS_START CONSTANT VARCHAR2(20) := 'start'; */
    DECLARE STR_STATUS_PROCESSING CONSTANT VARCHAR(20) = 'processing';  /* ORIGSQL: STR_STATUS_PROCESSING CONSTANT VARCHAR2(20) := 'processing'; */
    DECLARE STR_STATUS_FAIL CONSTANT VARCHAR(20) = 'fail';  /* ORIGSQL: STR_STATUS_FAIL CONSTANT VARCHAR2(20) := 'fail'; */
    DECLARE STR_STATUS_COMPLETED_SP CONSTANT VARCHAR(20) = 'completed_sp';  /* ORIGSQL: STR_STATUS_COMPLETED_SP CONSTANT VARCHAR2(20) := 'completed_sp'; */
    DECLARE STR_STATUS_COMPLETED_SH CONSTANT VARCHAR(20) = 'completed_sh';  /* ORIGSQL: STR_STATUS_COMPLETED_SH CONSTANT VARCHAR2(20) := 'completed_sh'; */
	    
       --status: completed_sp
       IF P_STR_STATUS = STR_STATUS_COMPLETED_SP THEN
          UPDATE AIA_CB_BATCH_STATUS ST SET ST.STATUS=P_STR_STATUS,ISACTIVE='Y',UPDATEDATE=current_date WHERE ST.BATCHNUM=P_BATCH_NO;
       --status: completed_sh
       ELSEIF P_STR_STATUS = STR_STATUS_COMPLETED_SH THEN
          UPDATE AIA_CB_BATCH_STATUS ST SET ST.STATUS=P_STR_STATUS,ISACTIVE='N',UPDATEDATE=current_date WHERE ST.BATCHNUM=P_BATCH_NO;
       --status: fail
       ELSEIF P_STR_STATUS = STR_STATUS_FAIL THEN
          UPDATE AIA_CB_BATCH_STATUS ST SET ST.STATUS=P_STR_STATUS,ISACTIVE='N',UPDATEDATE=current_date WHERE ST.BATCHNUM=P_BATCH_NO;
       --status: processing
       ELSEIF P_STR_STATUS = STR_STATUS_PROCESSING THEN
          UPDATE AIA_CB_BATCH_STATUS ST SET ST.STATUS=P_STR_STATUS,UPDATEDATE=current_date WHERE ST.BATCHNUM=P_BATCH_NO;
      END IF;

      commit;

  END --sp_update_batch_status;
 
 
 
 
 