
CREATE PROCEDURE EXT.SP_XDL_INB_PAYEEADVTGENERICPROFILE (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'PayeeAdvtGenericProfile';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_PAYEEADVTGENERICPROFILE';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_TRIGGERBUNDLEBOOSTERDAILY (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'TriggerBundleBoosterDaily';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_TRIGGERBUNDLEBOOSTERDAILY';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_TRIGGERMOBILESERR2 (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'TriggerMobileSERR2';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_TRIGGERMOBILESERR2';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CUSTOMCUSTOMEREXPERIENCE (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'CustomCustomerExperience';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CUSTOMCUSTOMEREXPERIENCE';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_TRANSACTIONMMPSMARTHOMEINSTALLATIONS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'TransactionMMPSmarthomeInstallations';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_TRANSACTIONMMPSMARTHOMEINSTALLATIONS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_COGNOSSCIISIM (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'COGNOSSCIISIM';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_COGNOSSCIISIM';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_TRANSACTIONADVTREVENUE (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'TransactionAdvtRevenue';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_TRANSACTIONADVTREVENUE';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_RESETFILE (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ResetFile';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_RESETFILE';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_PREPAIDSCIIIDAREPORT (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'PrepaidSCIIIDAReport';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_PREPAIDSCIIIDAREPORT';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIICANCELLATIONORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIICancellationOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIICANCELLATIONORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIIBUNDLEORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIBundleOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIIBUNDLEORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_HRCENTRALSCIISALESMANPROFILE (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'HRCentralSCIISalesmanProfile';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_HRCENTRALSCIISALESMANPROFILE';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_EDWSCIICCOPROFILES (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'EDWSCIICCOProfiles';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_EDWSCIICCOPROFILES';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIICHANNELPARTNERMASTER (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIChannelPartnerMaster';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIICHANNELPARTNERMASTER';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIICHANNELPARTNERHIERARCHY (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIChannelPartnerHierarchy';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIICHANNELPARTNERHIERARCHY';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUEADVTREVENUETARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValueAdvtRevenueTarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUEADVTREVENUETARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUEBSCCVTARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValueBSCCVTarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUEBSCCVTARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUEEXTPREPAIDPRODUCTTARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValueExtPrepaidProductTarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUEEXTPREPAIDPRODUCTTARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUESTVTELESALESTARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValueSTVTeleSalesTarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUESTVTELESALESTARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUEINTERNALPOINTTARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValueInternalPointTarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUEINTERNALPOINTTARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUECSITARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValueCSITarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUECSITARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUESTVTELESALESPROTECTEDCOMM (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValueSTVTeleSalesProtectedComm';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUESTVTELESALESPROTECTEDCOMM';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUEDIRECTSALESTARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValueDirectSalesTarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUEDIRECTSALESTARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUEINTERNALCEADJUSTMENT (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValueInternalCEAdjustment';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUEINTERNALCEADJUSTMENT';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CONCERTOSCIIDEREGISTRATION (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ConcertoSCIIDeRegistration';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CONCERTOSCIIDEREGISTRATION';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CPBSSSCIIMCASHSETTLEMENT (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'CPBSSSCIImCashSettlement';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CPBSSSCIIMCASHSETTLEMENT';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CONCERTOSCIISIMREGISTRATIONTRANSACTIONS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ConcertoSCIISIMRegistrationtransactions';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CONCERTOSCIISIMREGISTRATIONTRANSACTIONS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_SAPSCIIPHOENIXCARD (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'SAPSCIIPhoenixCard';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_SAPSCIIPHOENIXCARD';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_SAPSCIIPREPAIDSIM (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'SAPSCIIPrepaidSIM';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_SAPSCIIPREPAIDSIM';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_SAPSCIIBULKSALESZYRPT212 (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'SAPSCIIBulkSalesZYRPT212';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_SAPSCIIBULKSALESZYRPT212';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_SAPSCIIEQUIPMENTPRICE (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'SAPSCIIEquipmentprice';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_SAPSCIIEQUIPMENTPRICE';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_EMTUSCIIPREPAIDCREDITPURCHASE (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'EMTUSCIIPrepaidCreditPurchase';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_EMTUSCIIPREPAIDCREDITPURCHASE';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_SINGTELDASHSCIIDASH (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'SingtelDashSCIIDash';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_SINGTELDASHSCIIDASH';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_POSITIONRELATIONDIRECTSALESDEALERAMMAPPING (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'PositionRelationDirectSalesDealerAMMapping';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_POSITIONRELATIONDIRECTSALESDEALERAMMAPPING';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_POSITIONRELATIONCSIDEALERAMMAPPING (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'PositionRelationCSIDealerAMMapping';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_POSITIONRELATIONCSIDEALERAMMAPPING';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_HRCENTRALSCIILEAVEDETAILS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'HRCentralSCIILeaveDetails';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_HRCENTRALSCIILEAVEDETAILS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_ITDMSCIIPREPAIDTOPUP (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ITDMSCIIPrepaidTopup';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_ITDMSCIIPREPAIDTOPUP';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_ECMSSCIIMANUALTOPUP (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ECMSSCIIManualTopup';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_ECMSSCIIMANUALTOPUP';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIICSTICHANGEORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIICSTIChangeOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIICSTICHANGEORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CUSTOMVPVENDORSUMMARY (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'CustomVPVendorSummary';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CUSTOMVPVENDORSUMMARY';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CUSTOMVPVENDORDETAIL (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'CustomVPVendorDetail';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CUSTOMVPVENDORDETAIL';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_EDWPREPAIDSIM (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'EDWPrepaidSIM';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_EDWPREPAIDSIM';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_ATOMICSCIISINGTELMUSIC (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'AtomicSCIISingtelMusic';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_ATOMICSCIISINGTELMUSIC';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CLASSIFIERDEREGELIGIBLEDEALERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ClassifierDeregEligibleDealers';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CLASSIFIERDEREGELIGIBLEDEALERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CUSTOMNONWORKINGDAYS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'CustomNonWorkingDays';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CUSTOMNONWORKINGDAYS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CLASSIFIEREXTPREPAIDELIGIBLEDEALERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ClassifierExtPrepaidEligibleDealers';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CLASSIFIEREXTPREPAIDELIGIBLEDEALERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CLASSIFIERMOBILEROADSHOW (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ClassifierMobileRoadshow';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CLASSIFIERMOBILEROADSHOW';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CLASSIFIERROADSHOW (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ClassifierRoadshow';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CLASSIFIERROADSHOW';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CLASSIFIERROADSHOWSALESMANMAP (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ClassifierRoadshowSalesmanMap';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CLASSIFIERROADSHOWSALESMANMAP';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_POSITIONRELATIONSTVTELESALESDEALERAMMAPPING (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'PositionRelationSTVTeleSalesDealerAMMapping';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_POSITIONRELATIONSTVTELESALESDEALERAMMAPPING';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_EDWSCIIPREPAIDBBOM (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'EDWSCIIPrepaidBBOM';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_EDWSCIIPREPAIDBBOM';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_EDWSCIIPREPAIDVOICEACTIVATION (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'EDWSCIIPrepaidVoiceActivation';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_EDWSCIIPREPAIDVOICEACTIVATION';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_ODSSALESORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ODSSalesOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_ODSSALESORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_PREPAIDSCIIRMT0081 (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'PrepaidSCIIRMT0081';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_PREPAIDSCIIRMT0081';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_TRANSACTIONLIVECHATREVENUE (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'TransactionLivechatRevenue';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_TRANSACTIONLIVECHATREVENUE';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_MDLTMREMITREGISTRATIONTARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'MDLTmRemitRegistrationTarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_MDLTMREMITREGISTRATIONTARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUEMREMITPARTTIMERWORKINGHOURS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValuemRemitPartTimerWorkingHours';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUEMREMITPARTTIMERWORKINGHOURS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_MDLTINTERNALPRODUCTTARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'MDLTInternalProductTarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_MDLTINTERNALPRODUCTTARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_MDLTDIGITELESALESPOINTTARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'MDLTDigiTelesalesPointTarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_MDLTDIGITELESALESPOINTTARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_TRANSACTIONSIMONLYREVENUE (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'TransactionSimOnlyRevenue';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_TRANSACTIONSIMONLYREVENUE';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_TIMIOSSCIIFTE (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'TIMIOSSCIIFTE';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_TIMIOSSCIIFTE';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_VSOPSCIIIMEI (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'VSOPSCIIIMEI';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_VSOPSCIIIMEI';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_VSOPSCIIIMEIMATCHING (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'VSOPSCIIIMEIMatching';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_VSOPSCIIIMEIMATCHING';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIIVOUCHERINFO (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIVoucherInfo';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIIVOUCHERINFO';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIIMTPOSSALESORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIMTPOSSalesOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIIMTPOSSALESORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIIDISCOUNTINFO (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIDiscountInfo';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIIDISCOUNTINFO';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_SCSSSCIIBSCSALESORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'SCSSSCIIBSCSalesOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_SCSSSCIIBSCSALESORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIISUBMITTEDBROADBANDORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIISubmittedBroadBandOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIISUBMITTEDBROADBANDORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIICLOSEDBROADBANDORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIClosedBroadBandOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIICLOSEDBROADBANDORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIISUBMITTEDMOBILEORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIISubmittedMobileOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIISUBMITTEDMOBILEORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIICLOSEDMOBILEORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIClosedMobileOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIICLOSEDMOBILEORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIISUBMITTEDTVORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIISubmittedTVOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIISUBMITTEDTVORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIICLOSEDTVORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIClosedTVOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIICLOSEDTVORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIICLOSEDSMARTHOMEORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIClosedSmartHomeOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIICLOSEDSMARTHOMEORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIISUBMITTEDSMARTHOMEORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIISubmittedSmartHomeOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIISUBMITTEDSMARTHOMEORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIIMTPOSSTOCKINFO (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIMTPOSStockInfo';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIIMTPOSSTOCKINFO';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIIEPCEXTRACT (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIEPCExtract';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIIEPCEXTRACT';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_POSITIONRELATIONPREPAIDINTERNALDEALERAMMAPPING (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'PositionRelationPrepaidInternalDealerAMMapping';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_POSITIONRELATIONPREPAIDINTERNALDEALERAMMAPPING';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BUILDROLLDOWNRELATIONSHIP (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BuildRolldownRelationship';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BUILDROLLDOWNRELATIONSHIP';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIICLOSEDFIXEDVOICESTANDALONEORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIClosedFixedVoiceStandaloneOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIICLOSEDFIXEDVOICESTANDALONEORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIISUBMITTEDFIXEDVOICESTANDALONEORDERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIISubmittedFixedVoiceStandaloneOrders';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIISUBMITTEDFIXEDVOICESTANDALONEORDERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CLASSIFIERDELELIGIBLEDEALERS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'ClassifierDELEligibleDealers';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CLASSIFIERDELELIGIBLEDEALERS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_TRIGGERVPRECON (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'TriggerVPRecon';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_TRIGGERVPRECON';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_TRIGGERINTERNALCONNCOUNTTRANSACTIONS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'TriggerInternalConnCountTransactions';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_TRIGGERINTERNALCONNCOUNTTRANSACTIONS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_EDWSCIIMREMITTRANSACTIONS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'EDWSCIImRemitTransactions';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_EDWSCIIMREMITTRANSACTIONS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUEMOBILESERGATARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValueMobileSERGATarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUEMOBILESERGATARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_EDWSCIIDASHSIGNUP (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'EDWSCIIDashSignUp';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_EDWSCIIDASHSIGNUP';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CUSTOMSCIIEZLINKDASH (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'CustomSCIIEZLinkDash';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CUSTOMSCIIEZLINKDASH';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_CUSTOMDASHMATCHING (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'CustomDashMatching';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_CUSTOMDASHMATCHING';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_EDWSCIIDASHTOPUP (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'EDWSCIIDashTopUp';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_EDWSCIIDASHTOPUP';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUEPREPAIDINTERNALMETRICWEIGHTS (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValuePrepaidInternalMetricWeights';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUEPREPAIDINTERNALMETRICWEIGHTS';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_FIXEDVALUEPREPAIDINTERNALPRODUCTTARGET (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'FixedValuePrepaidInternalProductTarget';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_FIXEDVALUEPREPAIDINTERNALPRODUCTTARGET';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;


CREATE PROCEDURE EXT.SP_XDL_INB_BCCSCIIODSDASHREGISTRATION (IN FILENAME varchar(120))
LANGUAGE SQLSCRIPT
AS
BEGIN

DECLARE v_FILE_TYPE NVARCHAR(500) := 'BCCSCIIODSDashRegistration';
DECLARE v_src_tbl varchar(200) :='SRC_XDL_INB_BCCSCIIODSDASHREGISTRATION';
DECLARE v_file_date TIMESTAMP :=CURRENT_TIMESTAMP;
DECLARE v_file_name varchar(500):= :FILENAME;
    
SET SESSION 'v_FILE_TYPE' = :v_FILE_TYPE;
SET SESSION 'v_file_date' = :v_file_date;
SET SESSION 'v_file_name' = :v_file_name;
SET SESSION 'v_src_tbl' = :v_src_tbl;

CALL EXT.STEL_INITIAL_DYNAMIC_LOAD();
-- CALL EXT.INBOUND_TRIGGER();

END;
