apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: use-azure-redis-cache
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: use-azure-redis-cache
  rules:
  - path: /.*
    accessStrategies:
    - config: {}
      handler: allow
    methods:
    - GET
    - POST
    service:
      name: use-azure-redis-cache
      port: 80