apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: use-azure-redis-cache
spec:
  runtime: nodejs16
  source:
    gitRepository: 
      url: https://github.com/SAP-samples/kyma-runtime-extension-samples.git
      baseDir: /azure-service-operator/function
      reference: main
  env:
    - name: REDIS_CACHE_KEY
      valueFrom:
        secretKeyRef:
          name: rediscache-{your-provided-name} #replace it with rediscache-{your redis cache name}
          key: primaryKey
    - name: REDIS_CACHE_NAME
      value: {your-provided-name} #replace it with your redis cache name
  resourceConfiguration:
    function:
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
status: {}
