apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: use-azure-redis-cache
spec:
  hosts:
  - {your-provided-name}.redis.cache.windows.net #replace it with your redis cache name
  location: MESH_EXTERNAL
  ports:
  - name: redis
    number: 6380
    protocol: TLS
  resolution: DNS