apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: updateorderstatus
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - POST
        - GET
      path: /.*
  service:
    host: updateorderstatus.<YOUR HOST>
    name: updateorderstatus
    port: 80