apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: c4c-user-prop-xsuaa
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: c4c-user-prop-xsuaa
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - HEAD
        - PATCH
      service:
        name: app-auth-proxy
        port: 80
