CREATE VIEW "EXT"."VW_LT_GST_RATE" ( "EFFECTIVESTARTDATE", "EFFECTIVEENDDATE", "VALUE" ) AS (SELECT  CS_MDLTCell.EFFECTIVESTARTDATE,
        CS_MDLTCell.EFFECTIVEENDDATE,
        CS_MDLTCell.VALUE
FROM CS_MDLTCell
INNER JOIN CS_RELATIONALMDLT
  ON CS_RELATIONALMDLT.name='LT_SG_GST'
AND CS_RELATIONALMDLT.REMOVEDATE=TO_DATE ('2200/01/01', 'YYYY/MM/DD')
INNER JOIN CS_MDLTDimension
  ON UPPER(CS_MDLTDimension.name) = UPPER ('Tx.CompDate')
 AND CS_MDLTDimension.REMOVEDATE=TO_DATE ('2200/01/01', 'YYYY/MM/DD')
 AND CS_RELATIONALMDLT.ruleelementseq = CS_MDLTDimension.ruleelementseq
INNER JOIN  CS_MDLTIndex
  ON CS_RELATIONALMDLT.ruleelementseq = CS_MDLTIndex.ruleelementseq
 AND CS_MDLTDimension.dimensionseq = CS_MDLTIndex.dimensionseq
 AND CS_MDLTIndex.REMOVEDATE=TO_DATE ('2200/01/01', 'YYYY/MM/DD')
 AND CS_MDLTCell.mdltseq = CS_MDLTDimension.ruleelementseq
WHERE CS_MDLTCell.REMOVEDATE=TO_DATE ('2200/01/01', 'YYYY/MM/DD')) WITH READ ONLY