

CREATE OR REPLACE PROCEDURE EXT.HSBC_SP_LOAD_REPORTMASTER ()
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
DEFAULT SCHEMA EXT
AS
/**************************************************************************************************
	THIS STORED PROCEDURE IS CALLED BY HSBC_SP_TXN_STAMPING CUSTOM CDL SETUP 

	REVISIONS:
	VER        DATE          AUTHOR            DESCRIPTION
	---------  -----------   ----------------  -----------------------------------------------------
	0.01       26-DEC-2023   DEEPAN      INITIAL CREATION

***************************************************************************************************/
BEGIN
	
	

    DECLARE V_PERIODROW ROW LIKE TCMP.CS_PERIOD;
	DECLARE V_PUROW ROW LIKE TCMP.CS_PROCESSINGUNIT;
    DECLARE V_OBJECTNAME  VARCHAR(255) := ::CURRENT_OBJECT_SCHEMA || '.' ||::CURRENT_OBJECT_NAME;
	DECLARE V_BUROW ROW LIKE TCMP.CS_BUSINESSUNIT;
	DECLARE V_UT ROW LIKE TCMP.CS_UNITTYPE;
	DECLARE V_ET ROW LIKE TCMP.CS_EVENTTYPE;
	DECLARE V_CALENDARROW ROW LIKE TCMP.CS_CALENDAR;
    DECLARE V_REMOVEDATE VARCHAR(255);
    DECLARE IN_PROCESSINGUNITSEQ VARCHAR(255);
    DECLARE  IN_PERIODSEQ VARCHAR(255);
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
	BEGIN
		CALL EXT.HSBC_SP_DEBUG_WRITE(1, V_OBJECTNAME, 'EXITHANDLER.999', 'SQL_ERROR_CODE: '||::SQL_ERROR_CODE ||','||'SQL_ERROR_MESSAGE: '||::SQL_ERROR_MESSAGE, CURRENT_TIMESTAMP);
		RESIGNAL;
	END;
    
    V_REMOVEDATE:='2200-01-01';
    IN_PROCESSINGUNITSEQ:=38280596832649218;
    IN_PERIODSEQ=2533274790396334;
    
SELECT
	 CAST(SESSION_CONTEXT('GLOBVAR_IN_PERIODSEQ') AS DECIMAL(38,	10)) 
INTO IN_PERIODSEQ 
FROM SYS.DUMMY;

SELECT
	 CAST(SESSION_CONTEXT('GLOBVAR_IN_PROCESSINGUNITSEQ') AS DECIMAL(38,	10)) 
INTO IN_PROCESSINGUNITSEQ 
FROM SYS.DUMMY;


    
    -- SELECT * FROM CS_PERIOD WHERE NAME ='OCTOBER 2023' AND CALENDARSEQ=2251799813685250;
    
    -- SELECT * FROM CS_CALENDAR;
    

    SELECT * INTO V_BUROW  FROM CS_BUSINESSUNIT WHERE MASK='1';
	SELECT * INTO V_PUROW FROM TCMP.CS_PROCESSINGUNIT CP WHERE CP.PROCESSINGUNITSEQ = IN_PROCESSINGUNITSEQ;
	SELECT * INTO V_PERIODROW FROM TCMP.CS_PERIOD CP WHERE CP.PERIODSEQ = IN_PERIODSEQ AND CP.REMOVEDATE = V_REMOVEDATE AND CP.CALENDARSEQ=2251799813685250;
    SELECT * INTO V_ET FROM CS_EVENTTYPE WHERE EVENTTYPEID='Policy' AND REMOVEDATE = :V_REMOVEDATE;
    SELECT * INTO V_UT FROM CS_UNITTYPE WHERE NAME='SGD' AND REMOVEDATE = :V_REMOVEDATE;
    SELECT * INTO V_CALENDARROW FROM CS_CALENDAR WHERE NAME='Main Monthly Calendar' AND REMOVEDATE = :V_REMOVEDATE;
    
SELECT :V_PERIODROW.PERIODSEQ,
:V_PERIODROW.NAME,
:V_BUROW.NAME,
ST.CHANNEL,
CR.GENERICATTRIBUTE9 AS PAYCYCLEID ,-- "1" OR "2"
ST.COMPENSATIONDATE,
ST.GENERICATTRIBUTE23 AS SOURCESYSTEMTRANSACTIONCODE,
-- RIGHT (ST.GENERICATTRIBUTE17: 6-2-6 CODE, 6),
-- MID (ST.GENERICATTRIBUTE17: 6-2-6 CODE, 7,2),
-- LEFT (ST.GENERICATTRIBUTE17: 6-2-6 CODE, 6),
-- RIGHT (ST.GENERICATTRIBUTE17, 6),
-- MID (ST.GENERICATTRIBUTE17, 7,2),
-- LEFT (ST.GENERICATTRIBUTE17, 6),
CASE WHEN ST.GENERICATTRIBUTE2 = '1TOR' THEN TA.POSITIONNAME END,
CASE WHEN ST.GENERICATTRIBUTE3 = '2TOR' THEN TA.POSITIONNAME END,
POS.NAME,--OF CREDIT.PAYEE
ST.GENERICATTRIBUTE17, --: 6-2-6 CODE
SO.ORDERID,
ST.PONUMBER,
ST.GENERICATTRIBUTE24 AS ASSIGNCOMMISSIONFLAG,
-- LT_ASSIGN_FLAG_COMM_PERCENT WHERE DIM0 = <TA.GENERICATTRIBUTE1: BC> AND DIM1 = <ST.GENERICATTRIBUTE24: ASSIGN COMMISSION FLAG> AND DIM2 = 'DEFAULT' AND DIM3 = 1 AND TA.POSITION = CS_CREDIT.PAYEE
ET.EVENTTYPEID,
ST.GENERICDATE1 AS POLICYINCEPTIONDATE,
ST.GENERICDATE2 AS POLICYEFFECTIVEDATE,
ST.ACCOUNTINGDATE,
ST.GENERICATTRIBUTE15 AS BASEPLANCODE,
ST.GENERICATTRIBUTE18 AS COMPONENTPLANCODE,
ST.GENERICNUMBER5 AS PREMIUMYEAR,
ST.GENERICNUMBER6 AS PREMIUMTERM,
ST.GENERICATTRIBUTE2 AS PREMIUMTYPE,
ST.UNITTYPEFORVALUE,
ST.GENERICNUMBER2 AS EXCHANGERATE,
ST.UNITVALUE,
-- ST.NATIVEAMOUNT,--WHICH FIELD
-- ST.EXTENDEDNUMBER26 AS DISCOUNTPREMIUMAN,
TA.GENERICNUMBER1 AS SHARINGPERCENT,
ST.DATASOURCE,
ST.GENERICATTRIBUTE3 AS PRODUCTTYPE,
ST.GENERICATTRIBUTE5 AS TRANCHETYPE,
ST.GENERICATTRIBUTE20 AS GLFUNDTYPE,
ST.GENERICDATE4 AS PREMIUMPAIDTODATE,
IFNULL(ST.GENERICDATE6,ST.COMPENSATIONDATE) AS PREMIUMTRANSACTIONDATE
FROM 
CS_SALESTRANSACTION ST 
JOIN CS_CREDIT CR ON ST.SALESTRANSACTIONSEQ=CR.SALESTRANSACTIONSEQ
JOIN CS_TRANSACTIONASSIGNMENT TA ON TA.SALESTRANSACTIONSEQ=ST.SALESTRANSACTIONSEQ 
JOIN CS_POSITION POS ON POS.RULEELEMENTOWNERSEQ=CR.POSITIONSEQ AND TA.POSITIONNAME=POS.NAME AND POS.REMOVEDATE = :V_REMOVEDATE
JOIN CS_PAYEE PAY ON PAY.PAYEESEQ=POS.PAYEESEQ AND PAY.REMOVEDATE = :V_REMOVEDATE
JOIN CS_PARTICIPANT PAR ON PAR.PAYEESEQ=POS.PAYEESEQ AND PAR.PAYEESEQ=PAY.PAYEESEQ AND PAR.REMOVEDATE = :V_REMOVEDATE
JOIN CS_TITLE TI ON TI.RULEELEMENTOWNERSEQ=POS.TITLESEQ AND TI.REMOVEDATE = :V_REMOVEDATE
JOIN CS_SALESORDER SO ON SO.SALESORDERSEQ=ST.SALESORDERSEQ AND SO.REMOVEDATE = :V_REMOVEDATE
JOIN CS_EVENTTYPE ET ON ET.DATATYPESEQ=ST.EVENTTYPESEQ AND ET.REMOVEDATE = :V_REMOVEDATE
WHERE CR.PERIODSEQ=IN_PERIODSEQ
AND ST.COMPENSATIONDATE >=:V_PERIODROW.STARTDATE
AND ST.COMPENSATIONDATE < :V_PERIODROW.ENDDATE
AND TA.COMPENSATIONDATE >=:V_PERIODROW.STARTDATE
AND TA.COMPENSATIONDATE < :V_PERIODROW.ENDDATE;
-- AND ST.EVENTTYPESEQ=:V_ET.DATATYPESEQ;

END


