apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: conference-registration-app
  namespace: conference-registration
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: allow
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: conference-registration-app
    name: conference-registration-app
    port: 80