apiVersion: v1
kind: Service
metadata:
  name: conference-registration-app
  namespace: conference-registration
  labels:
    app: conference-registration-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: conference-registration-app