apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: cpi-scc-httpbin-neo
spec:
  env:
  - name: password
  - name: user
  - name: cpi_url
    value: https://<integration tenant>/http/httpbin/local
  runtime: nodejs16
  source:
    inline:
      dependencies: "{ \n  \"name\": \"cpi-scc-httpbin-neo\",\n  \"version\": \"1.0.0\",\n  \"dependencies\":
        {\n    \"axios\": \"^0.18.1\"\n  }\n}"
      source: "const axios = require(\"axios\");\n\nmodule.exports = { \n  main: async
        function (event, context) {\n    try{\n      const userpass = new Buffer.from(process.env.user
        + \":\" + process.env.password);\n      const userpassb64 = userpass.toString('base64');\n\n
        \     const body = {\n        \"somedata\": \"1234\"\n      };\n\n      var result
        = await axios.post(process.env.cpi_url, body, {\n          headers: {\n            Authorization:
        \"Basic\" + \" \" + userpassb64,\n            \"Content-Type\": \"application/json\"\n
        \         }\n        });\n      return result.data;\n    } catch (error) {\n      console.log(\"an
        error occurred: \", error);\n      return \"an error occurred...\";\n    }\n  }\n}\n"