apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: c4c-mock
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: c4c
  service:
    name: c4c-mock
    port: 10000
  rules:
    - path: /.*
      methods: ["GET", "POST", "PUT", "DELETE", "HEAD"]
      accessStrategies:
        - handler: noop