apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-extension-dotnet-minimalapi.fullname" . }}
  labels:
    {{- include "sample-extension-dotnet-minimalapi.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sample-extension-dotnet-minimalapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-extension-dotnet-minimalapi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
