CREATE VIEW "EXT"."STEL_LOOKUP_HANDLINGFEE" ( "NAME", "MDLTCELLSEQ", "EFFECTIVESTARTDATE", "EFFECTIVEENDDATE", "VALUE", "STRINGVALUE", "DATEVALUE", "DIM0", "DIM1", "DIM2", "DIM3", "DIM4", "DIM5" ) AS (SELECT   /* ORIGSQL: SELECT NAME,MDLTCELLSEQ,EFFECTIVESTARTDATE,EFFECTIVEENDDATE,VALUE,STRINGVALUE,DA(...) */
        NAME,
        MDLTCELLSEQ,
        EFFECTIVESTARTDATE,
        EFFECTIVEENDDATE,
        VALUE,
        STRINGVALUE,
        DATEVALUE,
        DIM0,
        'Handling Fee' AS DIM1,
        DIM2,
        DIM3,
        DIM4,
        DIM5
    FROM
        EXT.STEL_LOOKUP
    WHERE
        NAME = 'LT_CSI_Internal Products_D2D_Rates'
        AND DIM1 = 'TV GA'
        AND DIM3 = 'Override')