apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: sample-extension-micronaut
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: sample-extension-micronaut
  rules:
    - accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
      path: /.*
      service:
        name: sample-extension-micronaut
        port: 8080