apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: conference-registration
type: Opaque
stringData:
  HANA_DB_USER: "DBADMIN"
  HANA_DB_PASSWORD: ""
  HANA_DB_HOST: "0a000aaa-0000-0000-0000-a0aa000a0aaa.hana.trial-us10.hanacloud.ondemand.com"
  HANA_DB_PORT: "443"