apiVersion: v1
kind: Service
metadata:
  name: registrations-rest-api
  namespace: conference-registration
  labels:
    app: registrations-rest-api
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: registrations-rest-api