CREATE VIEW "EXT"."VW_SALESTRANSACTION_SINGLE" ( "TENANTID", "SALESTRANSACTIONSEQ", "SALESORDERSEQ", "LINENUMBER", "SUBLINENUMBER", "EVENTTYPESEQ", "PIPELINERUNSEQ", "ORIGINTYPEID", "COMPENSATIONDATE", "BILLTOADDRESSSEQ", "SHIPTOADDRESSSEQ", "OTHERTOADDRESSSEQ", "ISRUNNABLE", "BUSINESSUNITMAP", "ACCOUNTINGDATE", "PRODUCTID", "PRODUCTNAME", "PRODUCTDESCRIPTION", "NUMBEROFUNITS", "UNITVALUE", "UNITTYPEFORUNITVALUE", "PREADJUSTEDVALUE", "UNITTYPEFORPREADJUSTEDVALUE", "VALUE", "UNITTYPEFORVALUE", "NATIVECURRENCY", "NATIVECURRENCYAMOUNT", "DISCOUNTPERCENT", "DISCOUNTTYPE", "PAYMENTTERMS", "PONUMBER", "CHANNEL", "ALTERNATEORDERNUMBER", "DATASOURCE", "REASONSEQ", "COMMENTS", "GENERICATTRIBUTE1", "GENERICATTRIBUTE2", "GENERICATTRIBUTE3", "GENERICATTRIBUTE4", "GENERICATTRIBUTE5", "GENERICATTRIBUTE6", "GENERICATTRIBUTE7", "GENERICATTRIBUTE8", "GENERICATTRIBUTE9", "GENERICATTRIBUTE10", "GENERICATTRIBUTE11", "GENERICATTRIBUTE12", "GENERICATTRIBUTE13", "GENERICATTRIBUTE14", "GENERICATTRIBUTE15", "GENERICATTRIBUTE16", "GENERICATTRIBUTE17", "GENERICATTRIBUTE18", "GENERICATTRIBUTE19", "GENERICATTRIBUTE20", "GENERICATTRIBUTE21", "GENERICATTRIBUTE22", "GENERICATTRIBUTE23", "GENERICATTRIBUTE24", "GENERICATTRIBUTE25", "GENERICATTRIBUTE26", "GENERICATTRIBUTE27", "GENERICATTRIBUTE28", "GENERICATTRIBUTE29", "GENERICATTRIBUTE30", "GENERICATTRIBUTE31", "GENERICATTRIBUTE32", "GENERICNUMBER1", "UNITTYPEFORGENERICNUMBER1", "GENERICNUMBER2", "UNITTYPEFORGENERICNUMBER2", "GENERICNUMBER3", "UNITTYPEFORGENERICNUMBER3", "GENERICNUMBER4", "UNITTYPEFORGENERICNUMBER4", "GENERICNUMBER5", "UNITTYPEFORGENERICNUMBER5", "GENERICNUMBER6", "UNITTYPEFORGENERICNUMBER6", "GENERICDATE1", "GENERICDATE2", "GENERICDATE3", "GENERICDATE4", "GENERICDATE5", "GENERICDATE6", "GENERICBOOLEAN1", "GENERICBOOLEAN2", "GENERICBOOLEAN3", "GENERICBOOLEAN4", "GENERICBOOLEAN5", "GENERICBOOLEAN6", "PROCESSINGUNITSEQ", "MODIFICATIONDATE", "UNITTYPEFORLINENUMBER", "UNITTYPEFORSUBLINENUMBER", "UNITTYPEFORNUMBEROFUNITS", "UNITTYPEFORDISCOUNTPERCENT", "UNITTYPEFORNATIVECURRENCYAMT", "MODELSEQ", "CUSTID", "CONTACT", "COMPANY", "AREACODE", "PHONE", "FAX", "ADDRESS1", "ADDRESS2", "ADDRESS3", "CITY", "STATE", "COUNTRY", "POSTALCODE", "INDUSTRY", "GEOGRAPHY", "ORDERID", "EVENTTYPEID", "RECONFLAG", "ORDERTYPE", "ORDERLINETYPE" ) AS (SELECT   /* ORIGSQL: select st.TENANTID,st.SALESTRANSACTIONSEQ,st.SALESORDERSEQ,st.LINENUMBER,st.SUBL(...) */
        st.TENANTID,
        st.SALESTRANSACTIONSEQ,
        st.SALESORDERSEQ,
        st.LINENUMBER,
        st.SUBLINENUMBER,
        st.EVENTTYPESEQ,
        st.PIPELINERUNSEQ,
        st.ORIGINTYPEID,
        st.COMPENSATIONDATE,
        st.BILLTOADDRESSSEQ,
        st.SHIPTOADDRESSSEQ,
        st.OTHERTOADDRESSSEQ,
        st.ISRUNNABLE,
        st.BUSINESSUNITMAP,
        st.ACCOUNTINGDATE,
        st.PRODUCTID,
        st.PRODUCTNAME,
        st.PRODUCTDESCRIPTION,
        st.NUMBEROFUNITS,
        st.UNITVALUE,
        st.UNITTYPEFORUNITVALUE,
        st.PREADJUSTEDVALUE,
        st.UNITTYPEFORPREADJUSTEDVALUE,
        st.VALUE,
        st.UNITTYPEFORVALUE,
        st.NATIVECURRENCY,
        st.NATIVECURRENCYAMOUNT,
        st.DISCOUNTPERCENT,
        st.DISCOUNTTYPE,
        st.PAYMENTTERMS,
        st.PONUMBER,
        st.CHANNEL,
        st.ALTERNATEORDERNUMBER,
        st.DATASOURCE,
        st.REASONSEQ,
        st.COMMENTS,
        st.GENERICATTRIBUTE1,
        st.GENERICATTRIBUTE2,
        st.GENERICATTRIBUTE3,
        st.GENERICATTRIBUTE4,
        st.GENERICATTRIBUTE5,
        st.GENERICATTRIBUTE6,
        st.GENERICATTRIBUTE7,
        st.GENERICATTRIBUTE8,
        st.GENERICATTRIBUTE9,
        st.GENERICATTRIBUTE10,
        st.GENERICATTRIBUTE11,
        st.GENERICATTRIBUTE12,
        st.GENERICATTRIBUTE13,
        st.GENERICATTRIBUTE14,
        st.GENERICATTRIBUTE15,
        st.GENERICATTRIBUTE16,
        st.GENERICATTRIBUTE17,
        st.GENERICATTRIBUTE18,
        st.GENERICATTRIBUTE19,
        st.GENERICATTRIBUTE20,
        st.GENERICATTRIBUTE21,
        st.GENERICATTRIBUTE22,
        st.GENERICATTRIBUTE23,
        st.GENERICATTRIBUTE24,
        st.GENERICATTRIBUTE25,
        st.GENERICATTRIBUTE26,
        st.GENERICATTRIBUTE27,
        st.GENERICATTRIBUTE28,
        st.GENERICATTRIBUTE29,
        st.GENERICATTRIBUTE30,
        st.GENERICATTRIBUTE31,
        st.GENERICATTRIBUTE32,
        st.GENERICNUMBER1,
        st.UNITTYPEFORGENERICNUMBER1,
        st.GENERICNUMBER2,
        st.UNITTYPEFORGENERICNUMBER2,
        st.GENERICNUMBER3,
        st.UNITTYPEFORGENERICNUMBER3,
        st.GENERICNUMBER4,
        st.UNITTYPEFORGENERICNUMBER4,
        st.GENERICNUMBER5,
        st.UNITTYPEFORGENERICNUMBER5,
        st.GENERICNUMBER6,
        st.UNITTYPEFORGENERICNUMBER6,
        st.GENERICDATE1,
        st.GENERICDATE2,
        st.GENERICDATE3,
        st.GENERICDATE4,
        st.GENERICDATE5,
        st.GENERICDATE6,
        st.GENERICBOOLEAN1,
        st.GENERICBOOLEAN2,
        st.GENERICBOOLEAN3,
        st.GENERICBOOLEAN4,
        st.GENERICBOOLEAN5,
        st.GENERICBOOLEAN6,
        st.PROCESSINGUNITSEQ,
        st.MODIFICATIONDATE,
        st.UNITTYPEFORLINENUMBER,
        st.UNITTYPEFORSUBLINENUMBER,
        st.UNITTYPEFORNUMBEROFUNITS,
        st.UNITTYPEFORDISCOUNTPERCENT,
        st.UNITTYPEFORNATIVECURRENCYAMT,
        st.MODELSEQ
        ,/* --, ta.setnumber, ta.positionname, ta.payeeid, ta.titlename */  tad.custid,
        tad.contact,
        tad.company,
        tad.areacode,
        tad.phone,
        tad.fax,
        tad.address1,
        tad.address2,
        tad.address3,
        tad.city,
        tad.state,
        tad.country,
        tad.postalcode,
        tad.industry,
        tad.geography,
        so.orderid,
        et.eventtypeid,
        st.genericattribute26 AS reconflag,/* --for bcc txns only */  st.genericattribute10 AS ordertype,
        st.genericattribute9 AS orderlinetype
    FROM
        cs_salestransaction st

        /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_TRANSACTIONADDRESS' not found */
    LEFT OUTER JOIN
        (
            SELECT   /* ORIGSQL: (select * from cs_transactionaddress where addresstypeseq = (SELECT addresstypes(...) */
            *
        FROM
            cs_transactionaddress
        WHERE
            addresstypeseq
            /* RESOLVE: Identifier not found: Table/view 'DBMTK_USER_NAME.CS_ADDRESSTYPE' not found */
            =
            (
                SELECT   /* ORIGSQL: (Select addresstypeseq from cs_addresstype where addresstypeid='BILLTO') */
                addresstypeseq
            FROM
                cs_addresstype
            WHERE
                addresstypeid = 'BILLTO'
        )
    ) AS tad
    ON st.salestransactionseq = tad.salestransactionseq
    AND st.tenantid = tad.tenantid
INNER JOIN
    cs_eventtype et
    ON et.removedate >CURRENT_TIMESTAMP   /* ORIGSQL: sysdate */
    AND et.datatypeseq = st.eventtypeseq
INNER JOIN
    cs_Salesorder so
    ON so.salesorderseq = st.salesorderseq
    AND so.tenantid = st.tenantid
    AND so.processingunitseq = st.processingunitseq
    AND so.removedate >CURRENT_TIMESTAMP   /* ORIGSQL: sysdate */
    AND so.modelseq = 0) WITH READ ONLY