apiVersion: v1
kind: ServiceAccount
metadata:
  name: saas-demo-service-account
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: saas-demo-role
rules:
- apiGroups: [""]
  resources: ["configmaps","services"]
  verbs: ["get","list","create","delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","create","delete"]
- apiGroups: ["gateway.kyma-project.io"]
  resources: ["apirules"]
  verbs: ["get","list","create","delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: saas-demo-role-binding
subjects:
- kind: ServiceAccount
  name: saas-demo-service-account
roleRef:
  kind: Role
  name: saas-demo-role
  apiGroup: rbac.authorization.k8s.io