apiVersion: v1
kind: Service
metadata:
  name: 'my-first-kyma-service'
  labels:
    app.kubernetes.io/name: ''
spec:
  ports:
    name: http
    port: 4004
  selector:
    app: 'bookshop'
    example : 'bookshop'

apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'my-first-kyma-service'
  # namespace: risk-management
  labels:
    app.kubernetes.io/name: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 'my-first-kyma-service'
  template:
    metadata:
      labels:
        app: 'my-first-kyma-service'
        sidecar.istio.io/inject: 'false'
    spec:
      imagePullSecrets: []
      containers:
        - name: 'my-first-kyma-service'
          image: 'deepan13/kyma:latest'
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m

# global:
#   domain: c173af2.kyma.ondemand.com
#   imagePullSecret: 
#     name: container-registry
# srv:
#   bindings:
#     db:
#       fromSecret: cpapp-db
#     auth:
#       serviceInstanceName: xsuaa
#   image:
#     repository: https://index.docker.io/cpapp-srv
#     tag: latest
#   resources:
#     limits:
#       ephemeral-storage: 1G
#       memory: 500M
#     requests:
#       ephemeral-storage: 1G
#       cpu: 500m
#       memory: 500M
#   health_check:
#     liveness:
#       path: /
#     readiness:
#       path: /
# hana_deployer:
#   image:
#     repository: https://index.docker.io/cpapp-hana-deployer
#     tag: latest
#   bindings:
#     hana:
#       fromSecret: cpapp-db
#   resources:
#     limits:
#       cpu: 2000m
#       memory: 1G
#     requests:
#       cpu: 1000m
#       memory: 1G
# xsuaa:
#   serviceOfferingName: xsuaa
#   servicePlanName: application
#   parameters:
#     xsappname: cpapp
#     role-collections:
#       - description: Manage Risks
#         name: RiskManager
#         role-template-references:
#           - '$XSAPPNAME.RiskManager'
#       - description: View Risks
#         name: RiskViewer
#         role-template-references:
#           - '$XSAPPNAME.RiskViewer'
#   config: xs-security.json

