apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: cpi-api-read-oauth
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: cpi-api-read-oauth
  service:
    name: orders-list-api
    port: 80
  rules:
  - accessStrategies:
    - config:
        required_scope:
        - read
      handler: oauth2_introspection
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*