apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: orders-list-api
spec:
  runtime: nodejs16
  source:
    inline:
      dependencies: "{ \n  \"name\": \"orders-list-api\",\n  \"version\": \"1.0.0\",\n  \"dependencies\":
        {\n  }\n}"
      source: |
        module.exports = { main: function (event, context) {
            const {response, request: {headers}} = event.extensions;
            response.setHeader("Content-Type", "application/json");
            return `[{"orderid": "00000001", "description": "First sample order", "amount": "100.00"},{"orderid": "00000002", "description": "Second sample order", "amount": "102.00"},{"orderid": "00000003", "description": "Third sample order", "amount": "402.00"}]`;
        } }