
DROP TABLE EXT.CTAS_ARBALANCE_ERROR;
CREATE COLUMN TABLE EXT.CTAS_ARBALANCE_ERROR (
    INVOICENUMBER VARCHAR(255),
    SERVICEORDERNUMBER NVARCHAR(255),
    DUEDATE VARCHAR(255),
    CUSTOMERID VARCHAR(255),
    BALANCEVALUE VARCHAR(255),
    ERRORCODE NVARCHAR(255),
    DESCRIPTION VARCHAR(1000)
) UNLOAD PRIORITY 5 AUTO MERGE