apiVersion: apps/v1
kind: Deployment
metadata:
  name: hanadb-nodejs 
  labels:
    app: hanadb-nodejs 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hanadb-nodejs 
  template:
    metadata:
      labels:
        app: hanadb-nodejs  
    spec:                  
      containers: 
      - image: jcawley5/hanadb-nodejs:latest
        name: hanadb-nodejs  
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
        env:
          - name: HDB_HOST
            valueFrom:
              configMapKeyRef:
                name: hanadb-nodejs 
                key: host
          - name: HDB_PORT
            valueFrom:
              configMapKeyRef:
                name: hanadb-nodejs
                key: port
          - name: HDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hanadb-nodejs
                key: password
          - name: HDB_USER
            valueFrom:
              secretKeyRef:
                name: hanadb-nodejs
                key: user
          - name: NODE_ENV
            value: production
---
apiVersion: v1
kind: Service
metadata:
  name: hanadb-nodejs 
  labels:
    app: hanadb-nodejs
spec:
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  selector:
    app: hanadb-nodejs 