/*
 * This file      : EXT.RPT_ADVT_IND_PS.PROCEDURE.sqlscript
 * Converted from : EXT.RPT_ADVT_IND_PS.PROCEDURE.plsql
 *
 * Source DBMS          : Oracle, version unknown
 * Source DB servername : -undefined-
 * Target DBMS          : SAP Hana 2 >= SP05 (SQLScript)
 *
 *
 * User config(id=101) : Include default configuration settings in header of generated files: Setting=yes
 * User config(id=423) : Report identifier upper/lowercase analysis: Setting=no
 * User config(id=330) : Case mapping for usernames: Setting=nomap
 * User config(id=331) : Case mapping for names of schema objects (tables,views,columns,indexes,sequences,etc.): Setting=nomap
 * User config(id=332) : Case mapping for names of SQL objects (procedures, functions; not for variables/parameters): Setting=nomap
 * User config(id=335) : Apply case mappings also when source DBMS is case-sensitive for identifiers: Setting=no
 * User config(id=211) : Include an 'ORIGSQL' comment with the original SQL in the converted SQL: Setting=yes
 * User config(id=212)*: Max. number of characters of original SQL in 'ORIGSQL' comment: Setting=200
 * User config(id=215) : Append 'NOT CONVERTED' comment to unconverted statements in the converted SQL: Setting=yes
 * User config(id=217) : Report additional details about some conversion categories, either for all files or only the totals: Setting=all
 * User config(id=218) : Report details ordered by functionality or by impact: Setting=functionality
 * User config(id=220) : Datatype to convert Oracle INT, INTEGER or SMALLINT (which have 38-digit precision): Setting=BIGINT
 * User config(id=221)*: Length to convert Oracle (VAR)CHAR(2) declared without length: Setting=255
 * User config(id=222)*: For variables/parameters, datatype to convert Oracle NUMBER declared without precision: Setting=decimal(38,10)
 * User config(id=223)*: For table/view columns, datatype to convert Oracle NUMBER declared without precision: Setting=decimal(38,10)
 * User config(id=224) : For variables/parameters, datatype to convert Oracle NUMBER declared with precision but without scale(see User Guide): Setting=optimized_integer
 * User config(id=225) : For table/view columns, datatype to convert Oracle NUMBER declared with precision but without scale(see User Guide): Setting=optimized_integer
 * User config(id=231) : Length to convert a CHAR/BINARY datatype exceeding the target DBMS length: Setting=MAX
 * User config(id=265)*: Convert Oracle packages to Hana User-Defined Libraries: Setting=yes
 * User config(id=290) : Default conversion of DBMS_OUTPUT.PUT_LINE/GET_LINE: Setting=print
 * User config(id=292) : Conversion of PRINT-style statements: Setting=sqlscript_print
 * User config(id=300) : Conversion of REF CURSOR output parameters in procedures called from the client app: Setting=table_variable
 * User config(id=310) : Generate a SQL SECURITY/EXECUTE AS clause for procedures/functions: Setting=yes
 * User config(id=320) : Ignore or keep the leading 'N' in Unicode string notation N'...': Setting=ignore
 * User config(id=441) : Generate identity columns as BY DEFAULT or ALWAYS: Setting=by_default
 * User config(id=380) : How aggressively to convert identifiers in SQL objects (higher=slower): Setting=medium
 * User config(id=382) : How to rename identifiers that are reserved words: delimited, or with a suffix: Setting=delimited
 * User config(id=383) : How to handle identifiers that are non-recommended words (e.g. ANSI-reserved): Setting=ignore
 * User config(id=385) : When to substitute a column alias with the expression, when referenced in the query(settings are cumulative): Setting=simple_expression
 * User config(id=600) : Schema for run-time components: Setting=sapdbmtk
 * User config(id=704) : Show warning counts in Hana when running run_ddl/run_sql generated shell scripts: Setting=yes
 * User config(id=720) : Include the original SQL code at the end of the converted file: Setting=no
 * User config(id=781) : Generate call to customizable procedure after each object creation: Setting=yes
 *   NB: Settings marked '*' are set to non-defaults (use config #101=no for condensed overview))
 *
 * Project directory : C:/HANAMigrations/STELEXT
 *
 *-----------------------------------------------------------------------------
 * Generated by SAP Advanced SQL Migration v.3.5.3 at 05-Jun-2024 10:58:22
 * (generated with: sapdbmtk convert, 64791)
 * SAP Advanced SQL Migration is property of SAP SE.
 *-----------------------------------------------------------------------------
 */
go
CALL sapdbmtk.sp_dbmtk_report_connect('EXT.RPT_ADVT_IND_PS.PROCEDURE.sqlscript') WITH HINT(IGNORE_PLAN_CACHE)
go

-- Verify the target database has the expected version (or later).
-- This proc aborts the script if the version is earlier than expected:
CALL sapdbmtk.sp_dbmtk_target_dbms_version_check('HANA', '2SP05', 'EXT.RPT_ADVT_IND_PS.PROCEDURE.sqlscript') WITH HINT(IGNORE_PLAN_CACHE)
go
CALL sapdbmtk.sp_dbmtk_hang_session  -- NB: hangs only when waiting for user to abort session with CTRL-C (message is printed first)
go

-- Verify Hana database being used
CALL sapdbmtk.sp_dbmtk_HANA_db_check()
go
CALL sapdbmtk.sp_dbmtk_hang_session  -- NB: hangs only when waiting for user to abort session with CTRL-C (message is printed first)
go

-- Verify we have the required permissions
CALL sapdbmtk.sp_dbmtk_target_permissions_check()
go
CALL sapdbmtk.sp_dbmtk_hang_session  -- NB: hangs only when waiting for user to abort session with CTRL-C (message is printed first)
go
DO BEGIN
	if exists (select * from SYS.USERS where user_name = upper('EXT')) THEN
		EXECUTE IMMEDIATE 'CONNECT EXT PASSWORD "BwYDo5ywgxT$F@nr"';
		SELECT 'Reconnected as user '''||SESSION_USER||'''' FROM SYS.DUMMY;
	END IF;
END
go
SET SCHEMA EXT
go

/********************* Converted SQL code starts here:*************************/

/*
 * This file was extracted from 'C:/HANAMigrations/STELEXT/OracleObjects/RPT_ADVT_IND_PS.sql'
 * at 05-Jun-2024 10:45:22 with the 'extract_offline' command of SAP Advanced SQL Migration v.3.5.3 (64791)
 * User config setting for 'extract_offline' (id=132) was '0'.
 */
go

--********** Creating procedure 'EXT.RPT_ADVT_IND_PS' ********************
/* ORIGSQL: CREATE OR REPLACE PROCEDURE RPT_ADVT_IND_PS (in_rpttype varchar2, IN_PERIODSEQ IN INTEGER, IN_PROCESSINGUNITSEQ IN INTEGER) AS v_Tenantid VARCHAR2(255) := 'STEL'; */
CREATE OR REPLACE PROCEDURE EXT.RPT_ADVT_IND_PS
(
    IN in_rpttype VARCHAR(255),   /* RESOLVE: Manual edits required: VARCHAR2 parameter(no length): user-configured length=255; adjust as needed */
                                  /* ORIGSQL: in_rpttype varchar2 */
    IN IN_PERIODSEQ BIGINT,   /* ORIGSQL: IN_PERIODSEQ IN INTEGER */
    IN IN_PROCESSINGUNITSEQ BIGINT     /* ORIGSQL: IN_PROCESSINGUNITSEQ IN INTEGER */
)
SQL SECURITY DEFINER
/*READS SQL DATA*/ -- this procedure cannot be read-only
AS
BEGIN
    /* sapdbmtk: one or more DECLARE statements below were moved upwards, before the first executable statement */
    DECLARE v_Tenantid VARCHAR(255) = 'STEL';  /* ORIGSQL: v_Tenantid VARCHAR2(255) := 'STEL'; */
    DECLARE v_Calendarname VARCHAR(255) = NULL;  /* ORIGSQL: v_Calendarname VARCHAR2(255) := NULL; */
    DECLARE v_calendarseq BIGINT;  /* ORIGSQL: v_calendarseq INTEGER; */
    DECLARE V_FV5 DECIMAL(38,10);  /* ORIGSQL: V_FV5 number; */
    DECLARE v_period cs_period%rowtype;;/* NOT CONVERTED! */  /* RESOLVE: Identifier not found: Table 'EXT.cs_period' not found (for %ROWTYPE declaration) */

    /* RESOLVE: Identifier not found: Table/view 'EXT.CS_CALENDAR' not found */

    SELECT
        NAME,
        CALENDARSEQ
    INTO
        v_Calendarname,
        v_calendarseq
    FROM
        CS_CALENDAR
    WHERE
        NAME = 'Singtel Monthly Calendar';

    /* RESOLVE: Identifier not found: Table/view 'EXT.CS_FIXEDVALUE' not found */
    /* RESOLVE: Identifier not found: Table/view 'EXT.CS_PERIOD' not found */
    SELECT
        (FV.VALUE*100)
    INTO
        V_FV5
    FROM
        CS_FIXEDVALUE FV,
        CS_PERIOD PER,
        CS_CALENDAR C
    WHERE
        FV.EFFECTIVESTARTDATE < PER.ENDDATE
        AND PER.CALENDARSEQ = C.CALENDARSEQ
        AND FV.EFFECTIVEENDDATE >= PER.ENDDATE
        AND FV.REMOVEDATE = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200','dd/mm/yyyy')  /* ORIGSQL: to_date('01/01/2200','dd/mm/yyyy') */
        AND PER.REMOVEDATE = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200','dd/mm/yyyy')  /* ORIGSQL: to_date('01/01/2200','dd/mm/yyyy') */
        AND PER.PERIODSEQ = :IN_PERIODSEQ
        AND FV.NAME = 'FV_Rev Acc Achv Cap'
        AND FV.PERIODTYPESEQ
        /* RESOLVE: Identifier not found: Table/view 'EXT.CS_PERIODTYPE' not found */
        IN
        (
            SELECT   /* ORIGSQL: (SELECT PERIODTYPESEQ FROM CS_PERIODTYPE WHERE NAME ='year') */
                PERIODTYPESEQ
            FROM
                CS_PERIODTYPE
            WHERE
                NAME = 'year'
        )
        AND FV.MODELSEQ = 0
        AND C.CALENDARSEQ = :v_calendarseq;

    SELECT *
    INTO
        v_period
    FROM
        cs_period
    WHERE
        periodseq = :IN_PERIODSEQ
        --and calendarseq=2251799813685251
        AND removedate >CURRENT_TIMESTAMP;  /* ORIGSQL: sysdate */

    /* ORIGSQL: DELETE FROM STELEXT.STEL_RPT_ADV_IND_PS WHERE PERIODSEQ = IN_PERIODSEQ AND PROCESSINGUNITSEQ = IN_PROCESSINGUNITSEQ; */
    DELETE
    FROM
        STELEXT.STEL_RPT_ADV_IND_PS
    WHERE
        PERIODSEQ = :IN_PERIODSEQ
        AND PROCESSINGUNITSEQ = :IN_PROCESSINGUNITSEQ;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    /* ORIGSQL: STEL_PROC_RPT_partitions (IN_PERIODSEQ, 'STEL_RPT_ADV_IND_PS') */
    CALL EXT.STEL_PROC_RPT_PARTITIONS(:IN_PERIODSEQ, 'STEL_RPT_ADV_IND_PS');

    -- managing table partitions

    ---insertion of Incentive values for section -1
    ------------------------------------------------

    /* RESOLVE: Identifier not found: Table/view 'EXT.CS_INCENTIVE' not found */
    /* RESOLVE: Identifier not found: Table/view 'EXT.STEL_POSPART_MASTER' not found */
    /* ORIGSQL: INSERT INTO STEL_RPT_ADV_IND_PS (TENANTID, PAYEESEQ, POSITIONSEQ, PERIODSEQ, CALENDARSEQ, PROCESSINGUNITSEQ, PROCESSINGUNIT, PAYEEID, CALENDARNAME, SECTION, HIREDATE, FIRSTNAME, MIDDLENAME, LASTNAME, (...) */
    INSERT INTO STEL_RPT_ADV_IND_PS
        (
            TENANTID,
            PAYEESEQ,
            POSITIONSEQ,
            PERIODSEQ,
            CALENDARSEQ,
            PROCESSINGUNITSEQ,
            PROCESSINGUNIT,
            PAYEEID,
            CALENDARNAME,
            SECTION,
            HIREDATE,
            FIRSTNAME,
            MIDDLENAME,
            LASTNAME,
            POSITIONNAME,
            COMMISSION,
            INDIVIUALTARGET_M1,
            TEAMTARGET_M2,
            AR_M3,
            /* ---ANNUAL_TARGET , */
            PERIODNAME,
            M1_WEIGHTAGE,
            M2_WEIGHTAGE,
            M3_WEIGHTAGE,
            YEARLY_CAP,
            TITLESEQ,
            TITLENAME,
            CREATEDATE
        )
        SELECT   /* ORIGSQL: (SELECT v_Tenantid, P.PAYEESEQ, P.POSITIONSEQ, P.PERIODSEQ, v_calendarseq, IN_PROCESSINGUNITSEQ, P.PROCESSINGUNITNAME, P.PAYEEID, v_Calendarname AS CALENDARNAME, '1', P.HIREDATE, P.FIRSTNAME, P.MIDDLE(...) */
            :v_Tenantid,
            P.PAYEESEQ,
            P.POSITIONSEQ,
            P.PERIODSEQ,
            :v_calendarseq,
            :IN_PROCESSINGUNITSEQ,
            P.PROCESSINGUNITNAME,
            P.PAYEEID,
            :v_Calendarname AS CALENDARNAME,
            '1',
            P.HIREDATE,
            P.FIRSTNAME,
            P.MIDDLENAME,
            P.LASTNAME,
            P.POSITIONNAME,
            SUM(
                CASE 
                    WHEN (I.GENERICATTRIBUTE1 = 'Advt_M1_Indv'
                    AND P.periodname NOT LIKE 'March%')
                    THEN I.GENERICNUMBER1
                    WHEN (I.GENERICATTRIBUTE1 IN('Advt_M2_Team/SA','Advt_M2_SA')
                    AND P.periodname LIKE 'March%')
                    THEN I.GENERICNUMBER1
                    ELSE 0
                END
            ) AS commission_OTI,
            SUM(
                CASE 
                    WHEN (I.GENERICATTRIBUTE1 = 'Advt_M1_Indv'
                    AND P.periodname NOT LIKE 'March%')
                    THEN I.GENERICNUMBER1
                    WHEN (I.GENERICATTRIBUTE1 IN('Advt_M2_Team/SA','Advt_M2_SA')
                    AND P.periodname LIKE 'March%')
                    THEN I.GENERICNUMBER1
                    ELSE 0
                END
                ) * SUM(
                CASE
                    WHEN I.GENERICATTRIBUTE1 = 'Advt_M1_Indv'
                    THEN I.GENERICNUMBER2
                    ELSE 0
                END
            ) AS INDIVIDUALTARGET_M1,
            SUM(
                CASE 
                    WHEN (I.GENERICATTRIBUTE1 = 'Advt_M1_Indv'
                    AND P.periodname NOT LIKE 'March%')
                    THEN 0
                    WHEN (I.GENERICATTRIBUTE1 IN('Advt_M2_Team/SA','Advt_M2_SA')
                    AND P.periodname LIKE 'March%')
                    THEN I.GENERICNUMBER1
                    ELSE 0
                END
                ) * SUM(
                CASE
                    WHEN I.GENERICATTRIBUTE1 IN('Advt_M2_Team/SA','Advt_M2_SA')
                    THEN I.GENERICNUMBER2
                    ELSE 0
                END
            ) AS TEAMTARGET_M2,
            SUM(
                CASE 
                    WHEN (I.GENERICATTRIBUTE1 = 'Advt_M1_Indv'
                    AND P.periodname NOT LIKE 'March%')
                    THEN 0
                    WHEN (I.GENERICATTRIBUTE1 IN('Advt_M2_Team/SA','Advt_M2_SA')
                    AND P.periodname LIKE 'March%')
                    THEN I.GENERICNUMBER1
                    ELSE 0
                END
                ) * SUM(
                CASE
                    WHEN I.GENERICATTRIBUTE1 IN('Advt_M3_AR','Advt_M3_PR')
                    THEN I.GENERICNUMBER2
                    ELSE 0
                END
            ) AS AR_M3,
            /* --P.SALARY, */
            /* --SUM(CASE WHEN  I.GENERICATTRIBUTE1 ='Advt_M1_Indv' THEN (I.GENERICNUMBER1 * I.GENERICNUMBER2) ELSE 0 END) AS INDIVIDDUALTARGET_M1, */
            /* --SUM((CASE WHEN  I.GENERICATTRIBUTE1 IN('Advt_M2_Team/SA','Advt_M2_SA') THEN (I.GENERICNUMBER1 * I.GENERICNUMBER2) ELSE 0 END)) AS TEAMTARGET_M2, */
            /* --SUM((CASE WHEN  I.GENERICATTRIBUTE1 IN('Advt_M3_AR','Advt_M3_PR') THEN  (I.GENERICNUMBER1 * I.GENERICNUMBER2) ELSE 0 END)) AS AR_M3, */
            /* ---SUM((CASE WHEN I.GENERICATTRIBUTE1 = 'Advt_Yearly_Accelerator' THEN I.GENERICNUMBER6 ELSE 0 END)) AS ANNUAL_TARGET, */
            P.PERIODNAME AS PERIODNAME,
            IFNULL(TO_VARCHAR(SUM((
                            CASE 
                                WHEN I.GENERICATTRIBUTE1 = 'Advt_M1_Indv'
                                THEN I.GENERICNUMBER2
                                ELSE 0
                            END
            )*100)),'') || '%' AS M1_WEIGHTAGE,
            IFNULL(TO_VARCHAR(SUM(((
                                CASE 
                                    WHEN I.GENERICATTRIBUTE1 IN('Advt_M2_Team/SA','Advt_M2_SA')
                                    THEN I.GENERICNUMBER2
                                    ELSE 0
                                END
            )*100))),'') || '%' AS M2_WEIGHTAGE,
            IFNULL(TO_VARCHAR(SUM(((
                                CASE 
                                    WHEN I.GENERICATTRIBUTE1 IN('Advt_M3_AR','Advt_M3_PR')
                                    THEN I.GENERICNUMBER2
                                    ELSE 0
                                END
            )*100))),'') || '%' AS M3_WEIGHTAGE,
            /* --SUM((CASE WHEN  I.GENERICATTRIBUTE1 ='Advt_Yearly_Accelerator' THEN I.GENERICNUMBER3 ELSE 0  END)*100)|| '%' AS YEARLY_CAP, */
            IFNULL(TO_VARCHAR(:V_FV5),'')||'%' AS YEARLY_CAP,
            P.TITLESEQ AS TITLESEQ,
            P.TITLE AS TITLENAME,
            CURRENT_TIMESTAMP AS CREATEDATE  /* ORIGSQL: SYSDATE */
        FROM
            CS_INCENTIVE I,
            STEL_POSPART_MASTER P
        WHERE
            I.PAYEESEQ = P.PAYEESEQ
            AND I.POSITIONSEQ = P.POSITIONSEQ
            AND I.PERIODSEQ = P.PERIODSEQ
            AND P.PERIODSEQ = :IN_PERIODSEQ
            AND P.PROCESSINGUNIT = :IN_PROCESSINGUNITSEQ
            AND I.GENERICATTRIBUTE1 IN('Advt_M1_Indv','Advt_M2_Team/SA','Advt_M3_AR','Advt_Yearly_Accelerator','Advt_M2_SA','Advt_M3_PR')
        GROUP BY
            P.PAYEESEQ,
            P.POSITIONSEQ,
            P.PERIODSEQ,
            P.PROCESSINGUNITNAME,
            P.PAYEEID,
            '1',
            P.HIREDATE,
            P.FIRSTNAME,
            P.MIDDLENAME,
            P.LASTNAME,
            P.POSITIONNAME,
            P.PERIODNAME,
            IFNULL(TO_VARCHAR(:V_FV5),'')||'%',
            P.TITLESEQ,
            P.TITLE
    ;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    ---updation of measurement values in section- 1
    ------------------------------------------------

    /* RESOLVE: Identifier not found: Table/view 'STELEXT.STEL_RPT_ADV_IND_PS' not found */
    /* ORIGSQL: UPDATE STELEXT.STEL_RPT_ADV_IND_PS T SET MIN_THRESHOLD_PERCENT = (SELECT M.GENERICATTRIBUTE7 FROM CS_MEASUREMENT M WHERE T.PAYEESEQ = M.PAYEESEQ AND T.PERIODSEQ = M.PERIODSEQ AND M.GENERICATTRIBUTE1 =(...) */
    UPDATE STELEXT.STEL_RPT_ADV_IND_PS T
        /* RESOLVE: Identifier not found: Table/view 'EXT.CS_MEASUREMENT' not found */
        SET
        /* ORIGSQL: MIN_THRESHOLD_PERCENT = */
        MIN_THRESHOLD_PERCENT = (
            SELECT   /* ORIGSQL: (SELECT M.GENERICATTRIBUTE7 FROM CS_MEASUREMENT M WHERE T.PAYEESEQ = M.PAYEESEQ AND T.PERIODSEQ = M.PERIODSEQ AND M.GENERICATTRIBUTE1 = 'Advt_Qtrly Rev Achv_Payable') */
                M.GENERICATTRIBUTE7
            FROM
                CS_MEASUREMENT M
            WHERE
                T.PAYEESEQ = M.PAYEESEQ
                AND T.PERIODSEQ = M.PERIODSEQ
                AND M.GENERICATTRIBUTE1 = 'Advt_Qtrly Rev Achv_Payable'
        ), 
        /* ORIGSQL: MIN_THRESHOLD_EXTRA_PERCENT = */
        MIN_THRESHOLD_EXTRA_PERCENT = (
            SELECT   /* ORIGSQL: (SELECT M.GENERICATTRIBUTE4 FROM CS_MEASUREMENT M WHERE T.PAYEESEQ = M.PAYEESEQ AND T.PERIODSEQ = M.PERIODSEQ AND M.GENERICATTRIBUTE1 = 'Advt_Qtrly Rev Achv_Payable') */
                M.GENERICATTRIBUTE4
            FROM
                CS_MEASUREMENT M
            WHERE
                T.PAYEESEQ = M.PAYEESEQ
                AND T.PERIODSEQ = M.PERIODSEQ
                AND M.GENERICATTRIBUTE1 = 'Advt_Qtrly Rev Achv_Payable'
        ), 
        /* ORIGSQL: QUARTERLY_CAP = */
        QUARTERLY_CAP = (
            SELECT   /* ORIGSQL: (SELECT M.GENERICATTRIBUTE6 FROM CS_MEASUREMENT M WHERE T.PAYEESEQ = M.PAYEESEQ AND T.PERIODSEQ = M.PERIODSEQ AND M.GENERICATTRIBUTE1 = 'Advt_Qtrly Rev Achv_Payable') */
                M.GENERICATTRIBUTE6
            FROM
                CS_MEASUREMENT M
            WHERE
                T.PAYEESEQ = M.PAYEESEQ
                AND T.PERIODSEQ = M.PERIODSEQ
                AND M.GENERICATTRIBUTE1 = 'Advt_Qtrly Rev Achv_Payable'
        ), 
        /* ORIGSQL: THRESHOLD_PAYMENT = */
        THRESHOLD_PAYMENT = (
            SELECT   /* ORIGSQL: (SELECT M.GENERICATTRIBUTE5 FROM CS_MEASUREMENT M WHERE T.PAYEESEQ = M.PAYEESEQ AND T.PERIODSEQ = M.PERIODSEQ AND M.GENERICATTRIBUTE1 = 'Advt_Qtrly Rev Achv_Payable') */
                M.GENERICATTRIBUTE5
            FROM
                CS_MEASUREMENT M
            WHERE
                T.PAYEESEQ = M.PAYEESEQ
                AND T.PERIODSEQ = M.PERIODSEQ
                AND M.GENERICATTRIBUTE1 = 'Advt_Qtrly Rev Achv_Payable'
        ), 
        /* ORIGSQL: ANNUAL_TARGET = */
        ANNUAL_TARGET = (
            SELECT   /* ORIGSQL: (SELECT M.GENERICNUMBER2 FROM CS_MEASUREMENT M WHERE T.PAYEESEQ = M.PAYEESEQ AND T.PERIODSEQ = M.PERIODSEQ AND M.GENERICATTRIBUTE1 = 'Advt YTD Achv') */
                M.GENERICNUMBER2
            FROM
                CS_MEASUREMENT M
            WHERE
                T.PAYEESEQ = M.PAYEESEQ
                AND T.PERIODSEQ = M.PERIODSEQ
                AND M.GENERICATTRIBUTE1 = 'Advt YTD Achv'
        )
    WHERE
        T.SECTION = 1;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    ---insertion of measurement for section -2
    -------------------------------------------           
    /* ORIGSQL: INSERT INTO STEL_RPT_ADV_IND_PS (TENANTID, PAYEESEQ, POSITIONSEQ, PERIODSEQ, CALENDARSEQ, PROCESSINGUNITSEQ, PROCESSINGUNIT, PAYEEID, CALENDARNAME, SECTION, FIRSTNAME, MIDDLENAME, LASTNAME, POSITIONNA(...) */
    INSERT INTO STEL_RPT_ADV_IND_PS
        (
            TENANTID,
            PAYEESEQ,
            POSITIONSEQ,
            PERIODSEQ,
            CALENDARSEQ,
            PROCESSINGUNITSEQ,
            PROCESSINGUNIT,
            PAYEEID,
            CALENDARNAME,
            SECTION,
            FIRSTNAME,
            MIDDLENAME,
            LASTNAME,
            POSITIONNAME,
            PERIODNAME,
            QUARTERS,
            QUARTERACHIEVEMENTS,
            QUARTERTARGETS,
            QUARTERACHIEVEDPERCENT,
            TITLESEQ,
            TITLENAME,
            CREATEDATE,
            sourceperiodseq, sourceperiodname
        )
        
            SELECT   /* ORIGSQL: (SELECT V_TENANTID, P.PAYEESEQ, P.POSITIONSEQ, v_period.periodseq, V_CALENDARSEQ, IN_PROCESSINGUNITSEQ, P.PROCESSINGUNITNAME, P.PAYEEID, V_CALENDARNAME AS CALENDARNAME, '2', P.FIRSTNAME, P.MIDDLENAME,(...) */
                :v_Tenantid,
                P.PAYEESEQ,
                P.POSITIONSEQ,
                v_period.periodseq,
                /* --       qtdata.PERIODSEQ, */
                :v_calendarseq,
                :IN_PROCESSINGUNITSEQ,
                P.PROCESSINGUNITNAME,
                P.PAYEEID,
                :v_Calendarname AS CALENDARNAME,
                '2',
                P.FIRSTNAME,
                P.MIDDLENAME,
                P.LASTNAME,
                P.POSITIONNAME,
                /* -- QTDATA.MONTHNAME AS PERIODNAME, */
                v_period.name AS periodname,
                QTDATA.QTR AS QUARTERS,
                SUM(QTDATA.QUARTERACHIEVEMENTS) AS QUARTERACHIEVEMENTS,
                SUM(QTDATA.QUARTERTARGETS) AS QUARTERTARGETS,
                SUM((QTDATA.QUARTERACHIEVEDPERCENT)*100) AS QUARTERACHIEVEDPERCENT,
                P.TITLESEQ AS TITLESEQ,
                P.TITLE AS TITLENAME,
                CURRENT_TIMESTAMP AS CREATEDATE,  /* ORIGSQL: SYSDATE */
                QTDATA.PERIODSEQ,
                QTDATA.MONTHNAME
            FROM
                STEL_POSPART_MASTER P,
                (
                    SELECT   /* ORIGSQL: (SELECT POSITIONSEQ, PERIODSEQ, QTRNAME, PAYEESEQ, SUM(QUARTERACHIEVEMENTS) AS QUARTERACHIEVEMENTS, SUM(QUARTERTARGETS) AS QUARTERTARGETS,SUM(QUARTERACHIEVEDPERCENT) AS QUARTERACHIEVEDPERCENT, QTR,END(...) */
                        POSITIONSEQ,
                        PERIODSEQ,
                        QTRNAME,
                        PAYEESEQ,
                        SUM(QUARTERACHIEVEMENTS) AS QUARTERACHIEVEMENTS,
                        SUM(QUARTERTARGETS) AS QUARTERTARGETS,
                        SUM(QUARTERACHIEVEDPERCENT) AS QUARTERACHIEVEDPERCENT,
                        QTR,
                        ENDDATE,
                        MONTHNAME,
                        GENERICATTRIBUTE1
                    FROM
                        (
                            SELECT   /* ORIGSQL: (SELECT MES.POSITIONSEQ, QTR.ENDDATE AS ENDDATE, QTR.NAME AS QTRNAME, MES.PAYEESEQ,PRD.NAME AS MONTHNAME,GENERICATTRIBUTE1, MES.GENERICNUMBER2 AS QUARTERACHIEVEMENTS, MES.GENERICNUMBER3 AS QUARTERTARG(...) */
                                MES.POSITIONSEQ,
                                QTR.ENDDATE AS ENDDATE,
                                QTR.NAME AS QTRNAME,
                                MES.PAYEESEQ,
                                PRD.NAME AS MONTHNAME,
                                GENERICATTRIBUTE1,
                                MES.GENERICNUMBER2 AS QUARTERACHIEVEMENTS,
                                MES.GENERICNUMBER3 AS QUARTERTARGETS,
                                MES.GENERICNUMBER4 AS QUARTERACHIEVEDPERCENT,
                                MES.PERIODSEQ,
                                sapdbmtk.sp_f_dbmtk_substring(QTR.NAME,0,2) AS QTR  /* ORIGSQL: SUBSTR(QTR.NAME,0,2) */
                            FROM
                                CS_MEASUREMENT MES,
                                CS_PERIOD PRD,
                                CS_PERIOD QTR
                            WHERE
                                MES.PERIODSEQ = PRD.PERIODSEQ
                                AND PRD.PARENTSEQ = QTR.PERIODSEQ
                                AND prd.periodseq IN
                                (
                                    SELECT   /* ORIGSQL: (SELECT periodseq FROM (SELECT periodseq, parentseq, startdate, enddate, name, periodtype FROM (SELECT pd.*, pt.name AS periodtype, cal.name AS calendarname FROM cs_period pd, cs_periodtype pt, cs_cal(...) */
                                        periodseq
                                    FROM
                                        (
                                            SELECT   /* ORIGSQL: (SELECT periodseq, parentseq, startdate, enddate, name, periodtype FROM (SELECT pd.*, pt.name AS periodtype, cal.name AS calendarname FROM cs_period pd, cs_periodtype pt, cs_calendar cal WHERE pd.peri(...) */
                                                periodseq,
                                                parentseq,
                                                startdate,
                                                enddate,
                                                name,
                                                periodtype
                                            FROM
                                                (
                                                    SELECT   /* ORIGSQL: (SELECT pd.*, pt.name periodtype, cal.name calendarname FROM cs_period pd, cs_periodtype pt, cs_calendar cal WHERE pd.periodtypeseq = pt.periodtypeseq AND pt.removedate > SYSDATE AND pd.calendarseq = (...) */
                                                        pd.*,
                                                        pt.name AS periodtype,
                                                        cal.name AS calendarname
                                                    FROM
                                                        cs_period pd,
                                                        cs_periodtype pt,
                                                        cs_calendar cal
                                                    WHERE
                                                        pd.periodtypeseq = pt.periodtypeseq
                                                        AND pt.removedate > CURRENT_TIMESTAMP   /* ORIGSQL: SYSDATE */
                                                        AND pd.calendarseq = cal.calendarseq
                                                        AND cal.removedate > CURRENT_TIMESTAMP   /* ORIGSQL: SYSDATE */
                                                        AND pd.removedate > CURRENT_TIMESTAMP   /* ORIGSQL: SYSDATE */
                                                ) AS src
                                                START WITH periodseq =
                                                (
                                                    SELECT   /* ORIGSQL: (SELECT periodseq FROM (SELECT periodseq, parentseq, startdate, enddate, name, periodtype FROM (SELECT pd.*, pt.name AS periodtype, cal.name AS calendarname FROM cs_period pd, cs_periodtype pt, cs_cal(...) */
                                                        periodseq
                                                    FROM
                                                        (
                                                            SELECT   /* ORIGSQL: (SELECT periodseq, parentseq, startdate, enddate, name, periodtype FROM (SELECT pd.*, pt.name AS periodtype, cal.name AS calendarname FROM cs_period pd, cs_periodtype pt, cs_calendar cal WHERE pd.peri(...) */
                                                                periodseq,
                                                                parentseq,
                                                                startdate,
                                                                enddate,
                                                                name,
                                                                periodtype
                                                            FROM
                                                                (
                                                                    SELECT   /* ORIGSQL: (SELECT pd.*, pt.name periodtype, cal.name calendarname FROM cs_period pd, cs_periodtype pt, cs_calendar cal WHERE pd.periodtypeseq = pt.periodtypeseq AND pt.removedate > SYSDATE AND pd.calendarseq = (...) */
                                                                        pd.*,
                                                                        pt.name AS periodtype,
                                                                        cal.name AS calendarname
                                                                    FROM
                                                                        cs_period pd,
                                                                        cs_periodtype pt,
                                                                        cs_calendar cal
                                                                    WHERE
                                                                        pd.periodtypeseq =
                                                                        pt.periodtypeseq
                                                                        AND pt.removedate >
                                                                        CURRENT_TIMESTAMP   /* ORIGSQL: SYSDATE */
                                                                        AND pd.calendarseq =
                                                                        cal.calendarseq
                                                                        AND cal.removedate >
                                                                        CURRENT_TIMESTAMP   /* ORIGSQL: SYSDATE */
                                                                        AND pd.removedate >
                                                                        CURRENT_TIMESTAMP   /* ORIGSQL: SYSDATE */
                                                                ) AS src
                                                                START WITH periodseq =
                                                                v_period.periodseq -- Parameter 1
                                                                /* RESOLVE: Syntax not supported in target DBMS: HANA does not support CONNECT BY: use HIERARCHY feature in HANA 2; rewrite with available HANA features. */
                                                                CONNECT BY PRIOR parentseq =
                                                                periodseq
                                                        ) AS dbmtk_corrname_10474
                                                    WHERE
                                                        periodtype = 'year'
                                                )
                                                /* RESOLVE: Syntax not supported in target DBMS: HANA does not support CONNECT BY: use HIERARCHY feature in HANA 2; rewrite with available HANA features. */
                                                CONNECT BY PRIOR periodseq = parentseq
                                        ) AS dbmtk_corrname_10477
                                    WHERE
                                        periodtype = 'month'
                                        AND enddate <= v_period.enddate -- Parameter 2
                                )
                                AND PRD.REMOVEDATE = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200', 'MM/DD/YYYY')  /* ORIGSQL: TO_DATE('01/01/2200', 'MM/DD/YYYY') */
                                AND QTR.REMOVEDATE = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200', 'MM/DD/YYYY')  /* ORIGSQL: TO_DATE('01/01/2200', 'MM/DD/YYYY') */
                                AND MES.GENERICATTRIBUTE1 = 'Advt_Qtrly Rev Achv_Payable'
                        ) AS dbmtk_corrname_10480
                    GROUP BY
                        POSITIONSEQ, PERIODSEQ, PAYEESEQ, QTR,ENDDATE, QTRNAME, MONTHNAME,GENERICATTRIBUTE1
                ) AS QTDATA
            WHERE
                QTDATA.PAYEESEQ = P.PAYEESEQ
                AND QTDATA.POSITIONSEQ = P.POSITIONSEQ
                AND P.PERIODSEQ = :IN_PERIODSEQ
                --AND QTDATA.PERIODSEQ IN (SELECT YTDPERIODSEQ FROM cs_periodcalendarytd WHERE periodseq = IN_PERIODSEQ AND calendarname =V_CALENDARNAME)
                --AND QTDATA.PERIODSEQ = IN_PERIODSEQ
                AND P.PROCESSINGUNIT = :IN_PROCESSINGUNITSEQ
                AND QTDATA.GENERICATTRIBUTE1 = 'Advt_Qtrly Rev Achv_Payable'
            GROUP BY
                P.PAYEESEQ,
                P.POSITIONSEQ,
                qtdata.PERIODSEQ,
                P.PROCESSINGUNITNAME,
                P.PAYEEID,
                P.FIRSTNAME,
                P.MIDDLENAME,
                P.LASTNAME,
                P.POSITIONNAME,
                '2',
                QTDATA.MONTHNAME,
                QTDATA.QTR,
                P.TITLESEQ,
                P.TITLE,
                CURRENT_TIMESTAMP   /* ORIGSQL: SYSDATE */
        ;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    --updation of payouts for section-2
    -----------------------------------   

    /* ORIGSQL: UPDATE STELEXT.STEL_RPT_ADV_IND_PS T SET PAYOUTS =nvl((SELECT nvl(i.value,0) FROM CS_INCENTIVE I WHERE I.PERIODSEQ = T.sourceperiodseq AND T.PAYEESEQ = I.PAYEESEQ AND I.GENERICATTRIBUTE1 = 'Advt_M1_In(...) */
    UPDATE STELEXT.STEL_RPT_ADV_IND_PS T
        SET
        /* ORIGSQL: PAYOUTS = */
        PAYOUTS = IFNULL   /* ORIGSQL: nvl((SELECT nvl(i.value,0) FROM CS_INCENTIVE I WHERE I.PERIODSEQ = T.sourceperiodseq AND T.PAYEESEQ = I.PAYEESEQ AND I.GENERICATTRIBUTE1 = 'Advt_M1_Indv'),0) */
        (
            (
                SELECT   /* ORIGSQL: (SELECT nvl(i.value,0) FROM CS_INCENTIVE I WHERE I.PERIODSEQ = T.sourceperiodseq AND T.PAYEESEQ = I.PAYEESEQ AND I.GENERICATTRIBUTE1 = 'Advt_M1_Indv') */
                    IFNULL(i.value,0)
                FROM
                    CS_INCENTIVE I
                WHERE
                    I.PERIODSEQ = T.sourceperiodseq
                    AND T.PAYEESEQ = I.PAYEESEQ
                    AND I.GENERICATTRIBUTE1 = 'Advt_M1_Indv'
            )
        ,0)
    WHERE
        T.SECTION = 2
        AND t.periodseq = v_period.periodseq;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    ----insertion of incentive values for section-3
    -------------------------------------------------   

    /* ORIGSQL: INSERT INTO STEL_RPT_ADV_IND_PS (TENANTID, PAYEESEQ, POSITIONSEQ, PERIODSEQ, CALENDARSEQ, PROCESSINGUNITSEQ, PROCESSINGUNIT, PAYEEID, CALENDARNAME, SECTION, FIRSTNAME, MIDDLENAME, LASTNAME, POSITIONNA(...) */
    INSERT INTO STEL_RPT_ADV_IND_PS
        (
            TENANTID,
            PAYEESEQ,
            POSITIONSEQ,
            PERIODSEQ,
            CALENDARSEQ,
            PROCESSINGUNITSEQ,
            PROCESSINGUNIT,
            PAYEEID,
            CALENDARNAME,
            SECTION,
            FIRSTNAME,
            MIDDLENAME,
            LASTNAME,
            POSITIONNAME,
            PERIODNAME,
            /* --OVERALL_FY_ACHIEVEMENT, */
            ANNUAL_OTI,
            /* --YEARLY_ACHIEVEMENTS, */
            /* -- YEARLY_ACHV_PERCENT , */
            PAYOUT,
            QUARTERS,
            M2_IS_ACHIEVED,
            M2_ACHIVED_INC,
            M3_IS_ACHIEVED,
            M3_ACHIEVED_INC,
            TITLESEQ,
            TITLENAME,
            CREATEDATE,
            ANNUAL_ACC_PERCENT,
            M1_PAYOUT
        )
        SELECT   /* ORIGSQL: (SELECT v_Tenantid, P.PAYEESEQ, P.POSITIONSEQ, P.PERIODSEQ, v_calendarseq, IN_PROCESSINGUNITSEQ, P.PROCESSINGUNITNAME, P.PAYEEID, v_Calendarname AS CALENDARNAME, '3', P.FIRSTNAME, P.MIDDLENAME, P.LAST(...) */
            :v_Tenantid,
            P.PAYEESEQ,
            P.POSITIONSEQ,
            P.PERIODSEQ,
            :v_calendarseq,
            :IN_PROCESSINGUNITSEQ,
            P.PROCESSINGUNITNAME,
            P.PAYEEID,
            :v_Calendarname AS CALENDARNAME,
            '3',
            P.FIRSTNAME,
            P.MIDDLENAME,
            P.LASTNAME,
            P.POSITIONNAME,
            P.PERIODNAME AS PERIODNAME,
            /* --SUM((CASE WHEN I.GENERICATTRIBUTE1 = 'Advt_Yearly_Accelerator' THEN I.GENERICNUMBER6 ELSE 0 END)) AS OVERALL_FY_ACHIEVEMENTS, */
            SUM(
                CASE 
                    WHEN I.GENERICATTRIBUTE1 IN('Advt_M3_AR','Advt_M3_PR')
                    THEN I.GENERICNUMBER1
                    ELSE 0
                END
            ) AS ANNUAL_OTI,
            /* --SUM((CASE WHEN I.GENERICATTRIBUTE1 = 'Advt_Yearly_Accelerator' THEN I.GENERICNUMBER5 ELSE 0 END)) AS YEARLY_ACHIEVEMENT, */
            /* --SUM((CASE WHEN I.GENERICATTRIBUTE1 = 'Advt_Yearly_Accelerator' THEN I.GENERICNUMBER4 ELSE 0 END)*100) AS YEARLY_ACHIEVED_PERCENT, */
            SUM(
                CASE 
                    WHEN I.GENERICATTRIBUTE1 = 'Advt_Yearly_Accelerator'
                    THEN I.VALUE
                    ELSE 0
                END
            ) AS PAYOUT,
            NULL AS QUARTERS,
            MAX(
                CASE 
                    WHEN (I.GENERICATTRIBUTE1 IN('Advt_M2_SA', 'Advt_M2_Team/SA')
                    AND I.GENERICBOOLEAN1 = 1)
                    THEN 'YES'
                    ELSE 'NO'
                END
            ) AS M2_IS_ACHIEVED,
            SUM(
                CASE 
                    WHEN I.GENERICATTRIBUTE1 IN('Advt_M2_SA', 'Advt_M2_Team/SA')
                    THEN I.VALUE
                    ELSE 0
                END
            ) AS M2_ACHIEVED_INC,
            MAX(
                CASE 
                    WHEN (I.GENERICATTRIBUTE1 IN('Advt_M3_AR','Advt_M3_PR')
                    AND I.GENERICBOOLEAN1 = 1)
                    THEN 'YES'
                    ELSE 'NO'
                END
            ) AS M3_IS_ACHIEVED,
            SUM(
                CASE 
                    WHEN I.GENERICATTRIBUTE1 IN('Advt_M3_AR','Advt_M3_PR')
                    THEN I.VALUE
                    ELSE 0
                END
            ) AS M3_ACHIEVED_INC,
            P.TITLESEQ AS TITLESEQ,
            P.TITLE AS TITLENAME,
            CURRENT_TIMESTAMP AS CREATEDATE,  /* ORIGSQL: SYSDATE */
            /* --(ADVT_IND_PAYMENT.ANNUAL_OTI * 1.2) +(ADVT_IND_PAYMENT.ANNUAL_OTI * 1.6)+(ADVT_IND_PAYMENT.ANNUAL_OTI * 2)+(ADVT_IND_PAYMENT.ANNUAL_OTI * 2.5)+(ADVT_IND_PAYMENT.ANNUAL_OTI * 3)  */
            MAX((
                    CASE 
                        WHEN I.GENERICATTRIBUTE1 = 'Advt_Yearly_Accelerator'
                        THEN I.GENERICNUMBER2
                        ELSE 0
                    END
            )*100) AS ANNUAL_ACC_PERCENT,
            NULL AS M1_PAYOUT
        FROM
            CS_INCENTIVE I,
            STEL_POSPART_MASTER P
        WHERE
            I.PAYEESEQ = P.PAYEESEQ
            AND I.POSITIONSEQ = P.POSITIONSEQ
            AND I.PERIODSEQ = :IN_PERIODSEQ
            AND P.PERIODSEQ = :IN_PERIODSEQ
            AND P.PROCESSINGUNIT = :IN_PROCESSINGUNITSEQ
            AND I.GENERICATTRIBUTE1 IN('Advt_M1_Indv','Advt_M2_Team/SA','Advt_M3_AR','Advt_Yearly_Accelerator','Advt_M3_PR','Advt_M2_SA')
        GROUP BY
            :v_Tenantid,
            P.PAYEESEQ,
            P.POSITIONSEQ,
            P.PERIODSEQ,
            :v_calendarseq,
            :IN_PROCESSINGUNITSEQ,
            P.PROCESSINGUNITNAME,
            P.PAYEEID,
            P.FIRSTNAME,
            P.MIDDLENAME,
            P.LASTNAME,
            P.POSITIONNAME,
            :v_Calendarname,
            '3',
            P.PERIODNAME,
            --(CASE WHEN (I.GENERICATTRIBUTE1 IN('Advt_M2_SA', 'Advt_M2_Team/SA') AND I.GENERICBOOLEAN1 = 1) THEN 'YES' ELSE 'NO' END),
            --(CASE WHEN (I.GENERICATTRIBUTE1 IN( 'Advt_M3_AR','Advt_M3_PR') AND I.GENERICBOOLEAN1 = 1) THEN 'YES' ELSE 'NO' END),
            P.TITLESEQ,
            P.TITLE,
            CURRENT_TIMESTAMP   /* ORIGSQL: SYSDATE */
    ;

    /* ORIGSQL: COMMIT; */
    COMMIT;  

    /* ORIGSQL: UPDATE STELEXT.STEL_RPT_ADV_IND_PS T SET M1_PAYOUT = (SELECT SUM(PAYOUTS) FROM STEL_RPT_ADV_IND_PS x where t.periodseq=x.periodseq and t.positionseq=x.positionseq and section=2) WHERE T.SECTION = 3 an(...) */
    UPDATE STELEXT.STEL_RPT_ADV_IND_PS T
        /* RESOLVE: Identifier not found: Table/view 'EXT.STEL_RPT_ADV_IND_PS' not found */
        SET
        /* ORIGSQL: M1_PAYOUT = */
        M1_PAYOUT = (
            SELECT   /* ORIGSQL: (select SUM(PAYOUTS) from STEL_RPT_ADV_IND_PS x where t.periodseq=x.periodseq and t.positionseq=x.positionseq and section=2) */
                SUM(PAYOUTS)
            FROM
                STEL_RPT_ADV_IND_PS x
            WHERE
                t.periodseq = x.periodseq
                AND t.positionseq = x.positionseq
                AND section = 2
        )
    WHERE
        T.SECTION = 3
        AND t.periodseq = v_period.periodseq;  

    /* ORIGSQL: UPDATE STEL_RPT_ADV_IND_PS T SET OVERALL_FY_ACHIEVEMENT = (SELECT M.GENERICNUMBER2 FROM CS_MEASUREMENT M WHERE T.PAYEESEQ = M.PAYEESEQ AND T.PERIODSEQ = M.PERIODSEQ AND M.GENERICATTRIBUTE1 = 'Advt YTD(...) */
    UPDATE STEL_RPT_ADV_IND_PS T 
        SET
        /* ORIGSQL: OVERALL_FY_ACHIEVEMENT = */
        OVERALL_FY_ACHIEVEMENT = (
            SELECT   /* ORIGSQL: (SELECT M.GENERICNUMBER2 FROM CS_MEASUREMENT M WHERE T.PAYEESEQ = M.PAYEESEQ AND T.PERIODSEQ = M.PERIODSEQ AND M.GENERICATTRIBUTE1 = 'Advt YTD Achv') */
                M.GENERICNUMBER2
            FROM
                CS_MEASUREMENT M
            WHERE
                T.PAYEESEQ = M.PAYEESEQ
                AND T.PERIODSEQ = M.PERIODSEQ
                AND M.GENERICATTRIBUTE1 = 'Advt YTD Achv'
        ), 
        /* ORIGSQL: YEARLY_ACHIEVEMENTS = */
        YEARLY_ACHIEVEMENTS = (
            SELECT   /* ORIGSQL: (SELECT M.GENERICNUMBER1 FROM CS_MEASUREMENT M WHERE T.PAYEESEQ = M.PAYEESEQ AND T.PERIODSEQ = M.PERIODSEQ AND M.GENERICATTRIBUTE1 = 'Advt YTD Achv') */
                M.GENERICNUMBER1
            FROM
                CS_MEASUREMENT M
            WHERE
                T.PAYEESEQ = M.PAYEESEQ
                AND T.PERIODSEQ = M.PERIODSEQ
                AND M.GENERICATTRIBUTE1 = 'Advt YTD Achv'
        ), 
        /* ORIGSQL: YEARLY_ACHV_PERCENT = */
        YEARLY_ACHV_PERCENT = (
            SELECT   /* ORIGSQL: (SELECT (M.VALUE*100) FROM CS_MEASUREMENT M WHERE T.PAYEESEQ = M.PAYEESEQ AND T.PERIODSEQ = M.PERIODSEQ AND M.GENERICATTRIBUTE1 = 'Advt YTD Achv') */
                (M.VALUE*100)
            FROM
                CS_MEASUREMENT M
            WHERE
                T.PAYEESEQ = M.PAYEESEQ
                AND T.PERIODSEQ = M.PERIODSEQ
                AND M.GENERICATTRIBUTE1 = 'Advt YTD Achv'
        )
    WHERE
        T.SECTION = 3;

    /* ORIGSQL: COMMIT; */
    COMMIT;

    --insertion of PR table section-4(sub-report)
    ---------------------------------------------   
    /* ORIGSQL: INSERT INTO STEL_RPT_ADV_IND_PS (TENANTID, PAYEESEQ, POSITIONSEQ, PERIODSEQ, CALENDARSEQ, PROCESSINGUNITSEQ, PROCESSINGUNIT, PAYEEID, CALENDARNAME, SECTION, FIRSTNAME, MIDDLENAME, LASTNAME, POSITIONNA(...) */
    INSERT INTO STEL_RPT_ADV_IND_PS
        (
            TENANTID,
            PAYEESEQ,
            POSITIONSEQ,
            PERIODSEQ,
            CALENDARSEQ,
            PROCESSINGUNITSEQ,
            PROCESSINGUNIT,
            PAYEEID,
            CALENDARNAME,
            SECTION,
            FIRSTNAME,
            MIDDLENAME,
            LASTNAME,
            POSITIONNAME,
            PERIODNAME,
            PR_RATINGS,
            PR_VALUE,
            TITLESEQ,
            TITLENAME,
            CREATEDATE
        )
        SELECT   /* ORIGSQL: (SELECT v_Tenantid, P.PAYEESEQ, P.POSITIONSEQ, P.PERIODSEQ, v_calendarseq, IN_PROCESSINGUNITSEQ, P.PROCESSINGUNITNAME, P.PAYEEID, v_Calendarname AS CALENDARNAME, '4', P.FIRSTNAME, P.MIDDLENAME, P.LAST(...) */
            :v_Tenantid,
            P.PAYEESEQ,
            P.POSITIONSEQ,
            P.PERIODSEQ,
            :v_calendarseq,
            :IN_PROCESSINGUNITSEQ,
            P.PROCESSINGUNITNAME,
            P.PAYEEID,
            :v_Calendarname AS CALENDARNAME,
            '4',
            P.FIRSTNAME,
            P.MIDDLENAME,
            P.LASTNAME,
            P.POSITIONNAME,
            v_period.name AS periodname,
            ('PR'|| IFNULL(LKP.DIM0,'')) AS PR_RATINGS,
            IFNULL(TO_VARCHAR(LKP.VALUE*100),'')||'%' AS PR_VALUE,
            P.TITLESEQ AS TITLESEQ,
            P.TITLE AS TITLENAME,
            CURRENT_TIMESTAMP AS CREATEDATE  /* ORIGSQL: SYSDATE */
        FROM
            STEL_LOOKUP LKP,
            STEL_POSPART_MASTER P,
            CS_PERIOD PER
        WHERE
            P.PERIODSEQ = PER.PERIODSEQ
            AND lkp.NAME = 'LT_Advt_TL/Direc_PR Rank'
            AND LKP.EFFECTIVESTARTDATE < PER.ENDDATE
            AND LKP.EFFECTIVEENDDATE > PER.STARTDATE
            AND PER.REMOVEDATE = sapdbmtk.sp_f_dbmtk_format_string_to_datetime('01/01/2200','MM/DD/YYYY')  /* ORIGSQL: TO_DATE('01/01/2200','MM/DD/YYYY') */
            AND PER.PERIODSEQ = :IN_PERIODSEQ
            AND P.PROCESSINGUNIT = :IN_PROCESSINGUNITSEQ
    ;

    /* ORIGSQL: COMMIT; */
    COMMIT;
END;
go
CALL sapdbmtk.sp_dbmtk_object_install_custom('procedure', 'EXT', 'RPT_ADVT_IND_PS') WITH HINT(IGNORE_PLAN_CACHE);
go

/*
 * end of 'EXT.RPT_ADVT_IND_PS.PROCEDURE.sqlscript'
 */
go



select p.periodseq, p.name from cs_period p,


(SELECT
m.name as PERIODNAME,
q.name as QUARTERNAME,
y.name as YEARNAME,
q.q_node_id as QTR_PERIODSEQ
    -- hierarchy_distance
FROM HIERARCHY (
    SOURCE (select periodseq as node_id , parentseq as parent_id, name 
    from cs_period where removedate ='2200-01-01' and periodtypeseq=2814749767106561) 
    START WHERE periodseq = 2533274790397180 ) m ,
    
    (select periodseq as q_node_id , parentseq as q_parent_id, name
    from cs_period where removedate ='2200-01-01' and periodtypeseq=2814749767106563
     ) q,
    
    (select periodseq as y_node_id , parentseq as y_parent_id, name
    from cs_period where removedate ='2200-01-01' and periodtypeseq=2814749767106569
     ) y

where m.parent_id =  q.q_node_id
and q.q_parent_id = y.y_node_id) src

where p.periodtypeseq=2814749767106561
and p.removedate = '2200-01-01'
and src.QTR_PERIODSEQ =p.parentseq;


    