apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: { { include "api-mssql-go.fullname" . } }
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: { { include "api-mssql-go.fullname" . } }
  service:
    name: { { include "api-mssql-go.fullname" . } }
    port: { { .Values.service.port } }
  rules:
    - path: /orders|/orders/.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
