--liquibase formatted sql

--changeset jcadby:KYN_TQ2COM_Sync1 splitStatements:false stripComments:false
--comment: Create table
create column table EXT.KYN_TQ2COM_Sync(
	run_key bigint not null generated by default as identity,
	run_date timestamp default current_timestamp,
	process_flag tinyint default 0 not null,
	territoryprogramseq bigint not null,
	territoryprogram_name varchar(127),
	territoryprogram_esd date,
	territoryprogram_eed date,
	territoryprogram_periodtype varchar(50),
	territoryprogram_calendar varchar(50),
	territoryprogram_periodseq bigint,
	territoryprogram_period varchar(50),
	semiannual_periodseq bigint,
	semiannual_name varchar(50),
	message varchar(4000),
	primary key (
		run_key
	)
);

--changeset jcadby:KYN_TQ2COM_Sync2 splitStatements:false stripComments:false
--comment: Comment table
comment on table EXT.KYN_TQ2COM_SYNC is 'Driver table for staging data to sync process from TnQ to Commissions';