
Navn    - PARTICIPANTNAME        
MA-NR  -PAYEEID
ASS-NR - POSITIONNAME - 
INDL-LØN  JANUAR - YEARLY_REDEMPTION_JANUARY
INDL-REAL JANUAR -YEARLY_REDEMPTION_JANUARY
INDL-LØN  FEBRUAR - YEARLY_REDEMPTION_FEBRUARY
INDL-REAL FEBRUAR - REALIZED_REDEMPTION_FEBRUARY
INDL-LØN  MARTS   -YEARLY_REDEMPTION_MARCH
INDL-REAL MARTS   - REALIZED_REDEMPTION_MARCH
INDL-LØN  APRIL   YEARLY_REDEMPTION_APRIL
INDL-REAL APRIL    REALIZED_REDEMPTION_APRIL
INDL-LØN  MAJ     YEARLY_REDEMPTION_MAY
INDL-REAL MAJ      REALIZED_REDEMPTION_MAY
INDL-LØN  JUNI    YEARLY_REDEMPTION_JUNE
INDL-REAL JUNI     REALIZED_REDEMPTION_JUNE
INDL-LØN  JULI    YEARLY_REDEMPTION_JULY
INDL-REAL JULI     REALIZED_REDEMPTION_JULY
INDL-LØN  AUGUST  YEARLY_REDEMPTION_AUGUST
INDL-REAL AUGUST   REALIZED_REDEMPTION_AUGUST
INDL-LØN  SEPTEMB YEARLY_REDEMPTION_SEPTEMBER
INDL-REAL SEPTEMB  REALIZED_REDEMPTION_SEPTEMBER
INDL-LØN  OKTOBER YEARLY_REDEMPTION_OCTOBER
INDL-REAL OKTOBER  REALIZEDREDEMPTION_OCTOBER
INDL-LØN  NOV.    YEARLY_REDEMPTION_NOVEMBER
INDL-REAL NOV.     REALIZED_REDEMPTION_NOVEMBER
INDL-LØN  DEC.    YEARLY_REDEMPTION_DECEMBER
INDL-REAL DEC.    REALIZED_REDEMPTION_DECEMBER
SKADE-INDL-MAL    -REDEMPTION_TARGET
SKADE-INDL-REAL   - REDEMPTION_PENSION_YTD
PORTEFOLJEUDV-MAL  - PORTFOLIO_TARGET
PORTEFOLJEUDV-REAL -REALIZED_PORTFOLIO_DEVELOPMENT
FLY-AFG           - 0
PORTEFOLJE-PRIMO  - PORTFOLIO_PRIMO
SERVICE-MAL       - SERVICE_TARGET
SERVICE-REAL      - REALIZED_SERVICE
LONSOMHED-REAL    - PROFITABILITY
NYE-KONTRAKT-REAL  - new_contracts
NYEKUNDER-MAL     - NEW_CUSTOMERS_TARGET
NYEKUNDER-REAL    - REALIZED_CUSTOMERS
EGNE-KONTRAKT-MAL- NEW_CONTRACTS_TARGET
EGNE-KONTRAKT-REAL -REALIZED_CONTRACTS


update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_JANUAR=0 where INDL_REAL_JANUAR is NULL;
update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_FEBRUAR=0 where INDL_REAL_FEBRUAR is NULL;
update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_MARTS=0 where INDL_REAL_MARTS is NULL;
update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_APRIL=0 where INDL_REAL_APRIL is NULL;
update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_MAJ=0 where INDL_REAL_MAJ is NULL;
update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_JUNI=0 where INDL_REAL_JUNI is NULL;
update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_JULI=0 where INDL_REAL_JULI is NULL;
update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_AUGUST=0 where INDL_REAL_AUGUST is NULL;
update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_SEPTEMB=0 where INDL_REAL_SEPTEMB is NULL;
update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_OKTOBER=0 where INDL_REAL_OKTOBER is NULL;
update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_NOV=0 where INDL_REAL_NOV is NULL;
update ext.TRYG_NOTES_EXTRACT ne set INDL_REAL_DEC=0 where INDL_REAL_DEC is NULL;




CREATE COLUMN TABLE EXT.TRYG_NOTES_EXTRACT(
	NAVN VARCHAR(255),
	MA_NR VARCHAR(255),
	S_NR VARCHAR(255),
	INDL_LON_JANUAR DECIMAL(25, 2) default 0,
	INDL_REAL_JANUAR DECIMAL(25, 2) default 0,
	INDL_LON_FEBRUAR DECIMAL(25, 2) default 0,
	INDL_REAL_FEBRUAR DECIMAL(25, 2) default 0,
	INDL_LON_MARTS DECIMAL(25, 2) default 0,
	INDL_REAL_MARTS DECIMAL(25, 2) default 0,
	INDL_LON_APRIL DECIMAL(25, 2) default 0,
	INDL_REAL_APRIL DECIMAL(25, 2) default 0,
	INDL_LON_MAJ DECIMAL(25, 2) default 0,
	INDL_REAL_MAJ DECIMAL(25, 2) default 0,
	INDL_LON_JUNI DECIMAL(25, 2) default 0,
	INDL_REAL_JUNI DECIMAL(25, 2) default 0,
	INDL_LON_JULI DECIMAL(25, 2) default 0,
	INDL_REAL_JULI DECIMAL(25, 2) default 0,
	INDL_LON_AUGUST DECIMAL(25, 2) default 0,
	INDL_REAL_AUGUST DECIMAL(25, 2) default 0,
	INDL_LON_SEPTEMB DECIMAL(25, 2) default 0,
	INDL_REAL_SEPTEMB DECIMAL(25, 2) default 0,
	INDL_LON_OKTOBER DECIMAL(25, 2) default 0,
	INDL_REAL_OKTOBER DECIMAL(25, 2) default 0,
	INDL_LON_NOV DECIMAL(25, 2) default 0,
	INDL_REAL_NOV DECIMAL(25, 2) default 0,
	INDL_LON_DEC DECIMAL(25, 2) default 0,
	INDL_REAL_DEC DECIMAL(25, 2) default 0,
	SKADE_INDL_MAL DECIMAL(25, 2) default 0,
	SKADE_INDL_REAL DECIMAL(25, 2) default 0,
	PORTEFOLJEUDV_MAL DECIMAL(25, 2) default 0,
	PORTEFOLJEUDV_REAL DECIMAL(25, 2) default 0 ,
	FLY_AFG INTEGER CS_INT DEFAULT 0 NOT NULL,
	PORTEFOLJE_PRIMO DECIMAL(25, 2) default 0,
	SERVICE_MAL DECIMAL(25, 2) default 0,
	SERVICE_REAL DECIMAL(25, 2) default 0,
	LONSOMHED_REAL DECIMAL(25, 2) default 0,
	NYE_KONTRAKT_REAL DECIMAL(25, 2) default 0,
	NYEKUNDER_MAL DECIMAL(25, 2) default 0,
	NYEKUNDER_REAL DECIMAL(25, 2) default 0,
	EGNE_KONTRAKT_MAL DECIMAL(25, 2) default 0,
	EGNE_KONTRAKT_REAL DECIMAL(25, 2) default 0
)
UNLOAD PRIORITY 5 AUTO MERGE;
