apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: ce-coffee
  name: ce-coffee
  namespace: default
spec:
  buildResources: {}
  deps: |-
    {
      "name": "ce-coffee",
      "version": "0.0.1",
      "dependencies": {}
    }
  maxReplicas: 1
  minReplicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  runtime: nodejs14
  source: "module.exports = {\n    main: function (event) {\n\t    console.log(event);\n
    \       return 'Hello ce-coffee';\n    }\n}"
---
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: ce-coffee
  namespace: default
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.commerce.coffee.required.v1
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.commerce.coffee.produced.v1
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.commerce.coffee.consumed.v1
  protocolsettings: {}
  sink: http://ce-coffee.default.svc.cluster.local
