
--liquibase formatted sql

--changeset deepan s:EXT.TRYG_CANCEL_TXNS splitStatements:false stripComments:false
--comment: Drop table

DROP TABLE EXT.TRYG_CANCEL_TXNS;

--liquibase formatted sql

--changeset deepan s:EXT.TRYG_CANCEL_TXNS splitStatements:false stripComments:false
--comment: Create table

CREATE COLUMN TABLE EXT.TRYG_CANCEL_TXNS (
    CLAWBACKTYPE VARCHAR(4) NOT NULL,
    ISPRIVATEAGENT BOOLEAN CS_INT NOT NULL,
    CANTXNS_ALTERNATEORDERNUMBER VARCHAR(40),
    CANC_POSITIONNAME VARCHAR(127),
    CANTXNS_SALESTRANSACTIONSEQ BIGINT CS_FIXED NOT NULL,
    CANTXNS_SALESORDERSEQ BIGINT CS_FIXED NOT NULL,
    CANTXNS_EVENTTYPESEQ BIGINT CS_FIXED NOT NULL,
    CANTXNS_LINENUMBER BIGINT CS_FIXED NOT NULL,
    CANTXNS_SUBLINENUMBER BIGINT CS_FIXED NOT NULL,
    CANTXNS_COMPDATE LONGDATE CS_LONGDATE NOT NULL,
    CANTXNS_OLD_PREMIUM DECIMAL(25, 10) CS_FIXED,
    CANTXNS_NEW_PREMIUM DECIMAL(25, 10) CS_FIXED,
    CANTXNS_POLICY_SDATE LONGDATE CS_LONGDATE,
    CANTXNS_POLICY_EDATE LONGDATE CS_LONGDATE,
    CANTXNS_POLICY_CDATE LONGDATE CS_LONGDATE,
    CANTXNS_POSITIONNAME VARCHAR(127),
    CANTXNS_POSITIONSEQ BIGINT CS_FIXED NOT NULL
) UNLOAD PRIORITY 5 AUTO MERGE;


comment on table EXT.TRYG_CANCEL_TXNS is 'New Table';
