CREATE FUNCTION ext.IS_NUMBER (inputval NVARCHAR(100))
RETURNS RETURNVAL INT
LANGUAGE SQLSCRIPT
AS
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        RETURNVAL := 0;
    END;

    BEGIN
        DECLARE NUM DECIMAL(38,10);
        SELECT CAST(:inputval AS DECIMAL(38,10)) INTO NUM FROM DUMMY;
        RETURNVAL := 1;
    END;
END