
DROP TABLE EXT.TRYG_NOTES_EXTRACT_INCENTIVE ;
CREATE COLUMN TABLE EXT.TRYG_NOTES_EXTRACT_INCENTIVE (
    PARTICIPANTNAME VARCHAR(100),
    PAYEEID VARCHAR(100),
    POSITIONNAME VARCHAR(100),
    TITLE VARCHAR(100),
    PERIOD VARCHAR(50),
    YEARLY_REDEMPTION DECIMAL(25, 2) CS_FIXED,
    REALIZED_REDEMPTION DECIMAL(25, 2) CS_FIXED,
    REDEMPTION_TARGET_YTD DECIMAL(25, 2) CS_FIXED,
    REDEMPTION_TARGET_PENSION_AGENTS DECIMAL(25, 2) CS_FIXED,
    REALIZED_REDEMPTION_YTD DECIMAL(25, 2) CS_FIXED,
    PORTFOLIO_TARGET DECIMAL(25, 2) CS_FIXED,
    REALIZED_PORTFOLIO_DEVELOPMENT DECIMAL(25, 2) CS_FIXED,
    PORTFOLIO_PRIMO DECIMAL(25, 2) CS_FIXED,
    SERVICE_TARGET DECIMAL(25, 2) CS_FIXED,
    REALIZED_SERVICE DECIMAL(25, 2) CS_FIXED,
    PROFITABILITY DECIMAL(25, 2) CS_FIXED,
    NEW_CONTRACTS DECIMAL(25, 2) CS_FIXED,
    NEW_CUSTOMERS_TARGET DECIMAL(25, 2) CS_FIXED,
    REALIZED_CUSTOMERS DECIMAL(25, 2) CS_FIXED,
    NEW_CONTRACTS_TARGET DECIMAL(25, 2) CS_FIXED,
    REALIZED_CONTRACTS DECIMAL(25, 2) CS_FIXED
) UNLOAD PRIORITY 5 AUTO MERGE;