DROP TABLE EXT.TRYG_BROKER_SALE ;
CREATE COLUMN TABLE EXT.TRYG_BROKER_SALE (
    POLICE VARCHAR(40) NOT NULL,
    PAID_DATE VARCHAR(5000),
    GL_PRAEMIE DECIMAL(25, 0) CS_FIXED,
    NY_PRAEMIE DECIMAL(25, 0) CS_FIXED
) UNLOAD PRIORITY 5 AUTO MERGE;