
DROP TABLE EXT.TRYG_SH_CLAWBACK_LKTB ;
CREATE COLUMN TABLE EXT.TRYG_SH_CLAWBACK_LKTB (
    TENANTID VARCHAR(4) NOT NULL,
    NAME VARCHAR(127) NOT NULL,
    DIM_NAME VARCHAR(127) NOT NULL,
    DIM_INDICES VARCHAR(255),
    VALUE DECIMAL(25, 10) CS_FIXED,
    CREATEDATE LONGDATE CS_LONGDATE NOT NULL,
    EXECUTIONDATE LONGDATE CS_LONGDATE
) UNLOAD PRIORITY 5 AUTO MERGE;