
DROP TABLE EXT.TRYG_SH_CLAWBACK_TXNS;
CREATE COLUMN TABLE EXT.TRYG_SH_CLAWBACK_TXNS (
    TENANTID VARCHAR(4),
    PROCESSINGUNITSEQ BIGINT CS_FIXED NOT NULL,
    PERIODSEQ BIGINT CS_FIXED NOT NULL,
    POSITIONNAME VARCHAR(127),
    POSITIONSEQ BIGINT CS_FIXED NOT NULL,
    ORDERID VARCHAR(40) NOT NULL,
    LINENUMBER BIGINT CS_FIXED NOT NULL,
    SUBLINENUMBER BIGINT CS_FIXED NOT NULL,
    EVENTTYPEID VARCHAR(40) NOT NULL,
    COMPENSATIONDATE LONGDATE CS_LONGDATE NOT NULL,
    ALTERNATEORDERNUMBER VARCHAR(40),
    SALESTRANSACTIONSEQ BIGINT CS_FIXED NOT NULL,
    TXN_TYPE VARCHAR(4) NOT NULL,
    TXN_VALUE DECIMAL(25, 10) CS_FIXED NOT NULL,
    CREDIT_VALUE INTEGER CS_INT NOT NULL,
    TILGANG VARCHAR(255),
    POLICY_PREV_VALUE DECIMAL(25, 10) CS_FIXED,
    POLICY_CURR_VALUE DECIMAL(25, 10) CS_FIXED,
    POLICY_START_DATE LONGDATE CS_LONGDATE,
    POLICY_CANCEL_DATE LONGDATE CS_LONGDATE,
    MODIFICATIONDATE LONGDATE CS_LONGDATE NOT NULL,
    EXECUTIONDATE LONGDATE CS_LONGDATE
) UNLOAD PRIORITY 5 AUTO MERGE;