
DROP TABLE EXT.TRYG_SH_SALESTXNS_POLICYCRDS;
CREATE COLUMN TABLE EXT.TRYG_SH_SALESTXNS_POLICYCRDS (
    ORDERID VARCHAR(40) NOT NULL,
    LINENUMBER BIGINT CS_FIXED NOT NULL,
    SUBLINENUMBER BIGINT CS_FIXED NOT NULL,
    EVENTTYPEID VARCHAR(40) NOT NULL,
    COMPENSATIONDATE LONGDATE CS_LONGDATE,
    SALESTRANSACTIONSEQ BIGINT CS_FIXED,
    ALTERNATEORDERNUMBER VARCHAR(40),
    PERIODSEQ BIGINT CS_FIXED NOT NULL,
    POSITIONNAME VARCHAR(127),
    POSITIONSEQ BIGINT CS_FIXED,
    CREDITVALUE DECIMAL(25, 10) CS_FIXED,
    UNITTYPEFORCREDITVALUE BIGINT CS_FIXED,
    LASTPAYMENTDATE LONGDATE CS_LONGDATE
) UNLOAD PRIORITY 5 AUTO MERGE;