apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  labels:
    app.kubernetes.io/name: hello-timer
  name: hello-timer
  namespace: default
spec:
  buildResources: {}
  deps: |-
    {
      "name": "hello-timer",
      "version": "0.0.1",
      "dependencies": {}
    }
  maxReplicas: 1
  minReplicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  runtime: nodejs14
  source: |-
    module.exports = {
        main: function (event, context) {
            const nowUTC = (new Date()).toISOString();
            console.log('run at', nowUTC);
            return nowUTC;
        }
    }
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-job-hello-timer
  namespace: default
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-trigger
              image: eu.gcr.io/kyma-project/external/curlimages/curl:7.70.0
              imagePullPolicy: IfNotPresent
              command:
                - sh
                - -c
                - |
                  curl hello-timer.default;
                  x=\$?; curl -fsI -X POST http://localhost:15020/quitquitquit && exit \$x
          restartPolicy: Never