CREATE FUNCTION ext.ISDATE (inputval NVARCHAR(100), format NVARCHAR(100))
RETURNS RETURNVAL INT
LANGUAGE SQLSCRIPT
AS
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
        RETURNVAL := 0;
    END;

    BEGIN
        DECLARE DT DATE;
        SELECT TO_DATE(:inputval, :format) INTO DT FROM DUMMY;
        RETURNVAL := 1;
    END;
END