global:
  domain: c-18e23d2.kyma.ondemand.com
  imagePullSecret:
    name: regcred
srv:
  bindings:
    db:
      fromSecret: starwars
      serviceInstanceName: hana
    messaging:
      serviceInstanceName: event-mesh
    destination:
      serviceInstanceName: 'destination'
  image:
    repository: ghcr.io/sap-samples/cap-hana-swapi-srv
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      cpu: 500m
      ephemeral-storage: 1G
      memory: 500M
  health_check:
    liveness:
      path: /
    readiness:
      path: /
  health:
    liveness:
      path: /
    readiness:
      path: /
hana_deployer:
  image:
    repository: ghcr.io/sap-samples/cap-hana-swapi-db
    tag: latest
  bindings:
    hana:
      fromSecret: starwars
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana-deployer:
  image:
    repository: <your-container-registry>/cap-hana-swapi-hana-deployer
    tag: latest
  bindings:
    hana:
      serviceInstanceName: hana
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
event-mesh:
  serviceOfferingName: enterprise-messaging
  servicePlanName: default
destination:
  serviceOfferingName: 'destination'
  servicePlanName: 'lite'
  parameters:
    version: '1.0.0'
