apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: api-mssql-go
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: api-mssql-go
  service:
    name: api-mssql-go
    port: 80
  rules:
    - path: /orders|/orders/.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - DELETE
