apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: cdc-extension
  namespace: cdc
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: {}
          handler: allow
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
      path: /.*
  service:
    host: cdc-extension
    name: cdc-extension
    port: 80
