name: CI/CD for ML Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Download and install Python 3.14.0-alpha.0 manually
      - name: Install Python 3.14.0-alpha.0
        run: |
          sudo apt update
          sudo apt install -y wget
          wget https://www.python.org/ftp/python/3.14.0/Python-3.14.0a0.tgz
          tar -xvf Python-3.14.0a0.tgz
          cd Python-3.14.0a0
          ./configure
          make
          sudo make install

      # Verify the installation
      - name: Check Python version
        run: python3 --version

      # Install dependencies
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the training script
      - name: Run ML model training
        run: python3 src/train.py

      # Run tests
      - name: Run tests
        run: pytest tests/
