apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: sample-ui5-app
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: sample-ui5-app
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
    service:
      name: kyma-identity-propagation-ui5
      port: 80
