DROP TABLE EXT.TRYG_IB_SALESTXNS_POLICYASSIGNS;
CREATE COLUMN TABLE EXT.TRYG_IB_SALESTXNS_POLICYASSIGNS (
    BATCHNAME VARCHAR(90) NOT NULL,
    ORDERID VARCHAR(40),
    LINENUMBER BIGINT CS_FIXED,
    SUBLINENUMBER BIGINT CS_FIXED,
    EVENTTYPEID VARCHAR(40),
    POSITIONNAME VARCHAR(127),
    ALTERNATEORDERNUMBER VARCHAR(40)
) UNLOAD PRIORITY 5 AUTO MERGE