apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: grpcorderserver
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: grpcorderserver
  service:
    name: grpcorderserver
    port: 50051
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: allow
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD