apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcorderserver
  labels:
    app: grpcorderserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcorderserver
  template:
    metadata:
      labels:
        app: grpcorderserver
    spec:
      containers:
      - name: grpcorderserver
        image: jcawley5/grpcorderserver
        env:
        - name: _GRPC_TOKEN_
          value: "12345678"
        ports:
        - name: grpc
          containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: grpcorderserver
spec:
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
  selector:
    app: grpcorderserver
  type: ClusterIP