name: CI/CD for ML Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the training script
      - name: Run ML model training
        run: |
          python src/train.py

      # (Optional) Run tests
      - name: Run tests
        run: |
          pytest tests/

      # (Optional) Archive model artifacts
      - name: Upload model artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: model-artifacts
          path: path/to/saved/model  # Adjust this to your model output path
