name: CI/CD for 50_CICD

on:
  push:
    paths:
      - '50_CICD/**'
  pull_request:
    paths:
      - '50_CICD/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./50_CICD

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'  # Adjust this to your needed Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        if [ -d tests ]; then
          pytest
        else
          echo "No tests directory found. Skipping tests."
        fi

    # Add more steps as needed for your specific CICD processes
    # For example, linting, building, deploying, etc.