
DROP TABLE EXT.TRYG_CLAWBACK_CREDITS;

CREATE COLUMN TABLE EXT.TRYG_CLAWBACK_CREDITS(
	CREDITSEQ BIGINT CS_FIXED NOT NULL,
	CLAWBACKTYPE VARCHAR(4) NOT NULL,
	PERIODSEQ BIGINT CS_FIXED NOT NULL,
	SALESTRANSACTIONSEQ BIGINT CS_FIXED NOT NULL,
	NAME VARCHAR(90),
	PREV_POSITIONNAME NVARCHAR(127) NOT NULL,
	CREDIT_VALUE DECIMAL(25, 10) CS_FIXED NOT NULL,
	CREDIT_COMPDATE LONGDATE CS_LONGDATE NOT NULL,
	PREV_SUBLINENUMBER BIGINT CS_FIXED NOT NULL,
	PREV_ALTERNATEORDERNUMBER VARCHAR(40) NOT NULL,
	PREV_COMPENSATIONDATE LONGDATE CS_LONGDATE NOT NULL,
	PREV_LATESTPREMIUM DECIMAL(25, 10) CS_FIXED NOT NULL,
	PREV_SALESTRANSACTIONSEQ BIGINT CS_FIXED NOT NULL,
	PREV_POLICY_SDATE LONGDATE CS_LONGDATE,
	PREV_POLICY_EDATE LONGDATE CS_LONGDATE,
	CANTXNS_ALTERNATEORDERNUMBER VARCHAR(40) NOT NULL,
	CANTXNS_SALESTRANSACTIONSEQ BIGINT CS_FIXED NOT NULL,
	CANTXNS_SALESORDERSEQ BIGINT CS_FIXED NOT NULL,
	CANTXNS_LINENUMBER BIGINT CS_FIXED NOT NULL,
	CANTXNS_SUBLINENUMBER BIGINT CS_FIXED NOT NULL,
	CANTXNS_COMPDATE LONGDATE CS_LONGDATE NOT NULL,
	CANTXNS_OLD_PREMIUM DECIMAL(25, 10) CS_FIXED,
	CANTXNS_NEW_PREMIUM DECIMAL(25, 10) CS_FIXED,
	CANTXNS_POLICY_SDATE LONGDATE CS_LONGDATE,
	CANTXNS_POLICY_EDATE LONGDATE CS_LONGDATE,
	CANTXNS_POLICY_CDATE LONGDATE CS_LONGDATE,
	CANTXNS_POSITIONNAME VARCHAR(127),
	CANTXNS_POSITIONSEQ BIGINT CS_FIXED NOT NULL,
	CREDIT_SUM DECIMAL(25, 10) CS_FIXED,
	ISPRIVATEAGENT BOOLEAN CS_INT
)
UNLOAD PRIORITY 5 AUTO MERGE;
