apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: cap-service
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: cap-service
  service:
    name: cap-service
    port: 4004
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
