apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: test-in-cluster-events
  labels:
    scenario: in-cluster-events
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: test-in-cluster-events
  rules:
    - accessStrategies:
        - handler: allow
          config: {}
      methods:
        - GET
      path: /.*
      service:
        name: producer
        port: 80