CREATE COLUMN TABLE EXT.CTAS_SPM_WFSHRS(
Partnerid VARCHAR(255),	
DailyHours VARCHAR(255),
PeriodDate VARCHAR(255));


CREATE COLUMN TABLE EXT.CTAS_SPM_ECHRS( 
Partnerid	VARCHAR(255),
PayPeriodStartDate VARCHAR(255),
PayPeriodEndDate VARCHAR(255),
TotalHours VARCHAR(255));
