name: CI/CD for 50_CICD

on:
  push:
    paths:
      - '50_CICD/**'
  pull_request:
    paths:
      - '50_CICD/**'
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./50_CICD

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Adjust this version as needed

    - name: Install dependency checking tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools pipdeptree

    - name: Check dependency compatibility
      run: |
        pip-compile requirements.txt --upgrade --output-file requirements_lock.txt --no-emit-index-url
        echo "Updated dependencies in requirements_lock.txt:"
        cat requirements_lock.txt
        echo "Dependency tree:"
        pipdeptree

    - name: Upload requirements_lock.txt
      uses: actions/upload-artifact@v3
      with:
        name: requirements_lock
        path: ./50_CICD/requirements_lock.txt

  build-and-test:
    needs: check-dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./50_CICD

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Adjust this version as needed

    - name: Download requirements_lock.txt
      uses: actions/download-artifact@v3
      with:
        name: requirements_lock
        path: ./50_CICD

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_lock.txt

    - name: Run tests
      run: |
        if [ -d "tests" ]; then
          pytest
        else
          echo "No tests directory found. Skipping tests."
        fi

    # Add any other specific steps for 50_CICD here
    - name: Run specific tasks for 50_CICD
      run: |
        # Add your specific commands here
        echo "Running specific tasks for 50_CICD"